/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_lwjgl_opengl_nv_NVRegisterCombiners2 */

#ifndef _Included_org_lwjgl_opengl_nv_NVRegisterCombiners2
#define _Included_org_lwjgl_opengl_nv_NVRegisterCombiners2
#ifdef __cplusplus
extern "C" {
#endif
#undef org_lwjgl_opengl_nv_NVRegisterCombiners2_GL_PER_STAGE_CONSTANTS_NV
#define org_lwjgl_opengl_nv_NVRegisterCombiners2_GL_PER_STAGE_CONSTANTS_NV 34101L
/*
 * Class:     org_lwjgl_opengl_nv_NVRegisterCombiners2
 * Method:    nglCombinerStageParameterfvNV
 * Signature: (IILjava/nio/FloatBuffer;I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_nv_NVRegisterCombiners2_nglCombinerStageParameterfvNV
  (JNIEnv *, jclass, jint, jint, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_nv_NVRegisterCombiners2
 * Method:    nglGetCombinerStageParameterfvNV
 * Signature: (IILjava/nio/FloatBuffer;I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_nv_NVRegisterCombiners2_nglGetCombinerStageParameterfvNV
  (JNIEnv *, jclass, jint, jint, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
