/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_lwjgl_input_GamePad */

#ifndef _Included_org_lwjgl_input_GamePad
#define _Included_org_lwjgl_input_GamePad
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: _00024assertionsDisabled */
/* Inaccessible static: PAD_UP */
/* Inaccessible static: PAD_DOWN */
/* Inaccessible static: PAD_LEFT */
/* Inaccessible static: PAD_RIGHT */
/* Inaccessible static: PAD_BUTTON0 */
/* Inaccessible static: PAD_BUTTON1 */
/* Inaccessible static: PAD_BUTTON2 */
/* Inaccessible static: PAD_BUTTON3 */
/* Inaccessible static: PAD_BUTTON4 */
/* Inaccessible static: PAD_BUTTON5 */
/* Inaccessible static: PAD_BUTTON6 */
/* Inaccessible static: PAD_BUTTON7 */
/* Inaccessible static: PAD_BUTTON8 */
/* Inaccessible static: created */
/* Inaccessible static: buttonDownBuffer */
/* Inaccessible static: buttonDownAddress */
/* Inaccessible static: readBuffer */
/* Inaccessible static: readBufferAddress */
/* Inaccessible static: button */
/* Inaccessible static: state */
/* Inaccessible static: class_000240 */
/*
 * Class:     org_lwjgl_input_GamePad
 * Method:    initIDs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_input_GamePad_initIDs
  (JNIEnv *, jclass);

/*
 * Class:     org_lwjgl_input_GamePad
 * Method:    nCreate
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_lwjgl_input_GamePad_nCreate
  (JNIEnv *, jclass);

/*
 * Class:     org_lwjgl_input_GamePad
 * Method:    nDestroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_input_GamePad_nDestroy
  (JNIEnv *, jclass);

/*
 * Class:     org_lwjgl_input_GamePad
 * Method:    nPoll
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_input_GamePad_nPoll
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_lwjgl_input_GamePad
 * Method:    nRead
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_lwjgl_input_GamePad_nRead
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_lwjgl_input_GamePad
 * Method:    nEnableBuffer
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_lwjgl_input_GamePad_nEnableBuffer
  (JNIEnv *, jclass);

/*
 * Class:     org_lwjgl_input_GamePad
 * Method:    nGetNumButtons
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_lwjgl_input_GamePad_nGetNumButtons
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
