/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_lwjgl_opengl_GLU */

#ifndef _Included_org_lwjgl_opengl_GLU
#define _Included_org_lwjgl_opengl_GLU
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_lwjgl_opengl_GLU
 * Method:    gluErrorString
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_lwjgl_opengl_GLU_gluErrorString
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_lwjgl_opengl_GLU
 * Method:    gluGetString
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_lwjgl_opengl_GLU_gluGetString
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_lwjgl_opengl_GLU
 * Method:    gluOrtho2D
 * Signature: (DDDD)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GLU_gluOrtho2D
  (JNIEnv *, jclass, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     org_lwjgl_opengl_GLU
 * Method:    gluPerspective
 * Signature: (DDDD)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GLU_gluPerspective
  (JNIEnv *, jclass, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     org_lwjgl_opengl_GLU
 * Method:    ngluPickMatrix
 * Signature: (DDDDLjava/nio/IntBuffer;I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GLU_ngluPickMatrix
  (JNIEnv *, jclass, jdouble, jdouble, jdouble, jdouble, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_GLU
 * Method:    gluLookAt
 * Signature: (DDDDDDDDD)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GLU_gluLookAt
  (JNIEnv *, jclass, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     org_lwjgl_opengl_GLU
 * Method:    ngluProject
 * Signature: (DDDLjava/nio/DoubleBuffer;ILjava/nio/DoubleBuffer;ILjava/nio/IntBuffer;ILjava/nio/DoubleBuffer;I)I
 */
JNIEXPORT jint JNICALL Java_org_lwjgl_opengl_GLU_ngluProject
  (JNIEnv *, jclass, jdouble, jdouble, jdouble, jobject, jint, jobject, jint, jobject, jint, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_GLU
 * Method:    ngluUnProject
 * Signature: (DDDLjava/nio/DoubleBuffer;ILjava/nio/DoubleBuffer;ILjava/nio/IntBuffer;ILjava/nio/DoubleBuffer;I)I
 */
JNIEXPORT jint JNICALL Java_org_lwjgl_opengl_GLU_ngluUnProject
  (JNIEnv *, jclass, jdouble, jdouble, jdouble, jobject, jint, jobject, jint, jobject, jint, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_GLU
 * Method:    ngluScaleImage
 * Signature: (IIIILjava/nio/ByteBuffer;IIIILjava/nio/ByteBuffer;I)I
 */
JNIEXPORT jint JNICALL Java_org_lwjgl_opengl_GLU_ngluScaleImage
  (JNIEnv *, jclass, jint, jint, jint, jint, jobject, jint, jint, jint, jint, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_GLU
 * Method:    ngluBuild1DMipmaps
 * Signature: (IIIIILjava/nio/ByteBuffer;I)I
 */
JNIEXPORT jint JNICALL Java_org_lwjgl_opengl_GLU_ngluBuild1DMipmaps
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_GLU
 * Method:    ngluBuild2DMipmaps
 * Signature: (IIIIIILjava/nio/ByteBuffer;I)I
 */
JNIEXPORT jint JNICALL Java_org_lwjgl_opengl_GLU_ngluBuild2DMipmaps
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
