/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_lwjgl_opengl_GLWindow */

#ifndef _Included_org_lwjgl_opengl_GLWindow
#define _Included_org_lwjgl_opengl_GLWindow
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: _00024assertionsDisabled */
/* Inaccessible static: currentWindow */
/* Inaccessible static: class_00024org_00024lwjgl_00024Window */
/*
 * Class:     org_lwjgl_opengl_GLWindow
 * Method:    swapBuffers
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GLWindow_swapBuffers
  (JNIEnv *, jobject);

/*
 * Class:     org_lwjgl_opengl_GLWindow
 * Method:    nCreate
 * Signature: (Ljava/lang/String;IIIIIIIIZ)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GLWindow_nCreate
  (JNIEnv *, jobject, jstring, jint, jint, jint, jint, jint, jint, jint, jint, jboolean);

/*
 * Class:     org_lwjgl_opengl_GLWindow
 * Method:    nDestroyGL
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GLWindow_nDestroyGL
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
