/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_lwjgl_opengl_CoreGL11 */

#ifndef _Included_org_lwjgl_opengl_CoreGL11
#define _Included_org_lwjgl_opengl_CoreGL11
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glAccum
 * Signature: (IF)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glAccum
  (JNIEnv *, jclass, jint, jfloat);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glAlphaFunc
 * Signature: (IF)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glAlphaFunc
  (JNIEnv *, jclass, jint, jfloat);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glClearColor
 * Signature: (FFFF)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glClearColor
  (JNIEnv *, jclass, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glClearAccum
 * Signature: (FFFF)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glClearAccum
  (JNIEnv *, jclass, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glClear
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glClear
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glCallLists
 * Signature: (IILjava/nio/Buffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glCallLists
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glCallList
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glCallList
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glBlendFunc
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glBlendFunc
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glBitmap
 * Signature: (IIFFFFLjava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glBitmap
  (JNIEnv *, jclass, jint, jint, jfloat, jfloat, jfloat, jfloat, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glBindTexture
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glBindTexture
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glBegin
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glBegin
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glEnd
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glEnd
  (JNIEnv *, jclass);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glArrayElement
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glArrayElement
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glAreTexturesResident
 * Signature: (ILjava/nio/IntBuffer;Ljava/nio/ByteBuffer;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_lwjgl_opengl_CoreGL11_glAreTexturesResident
  (JNIEnv *, jclass, jint, jobject, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glClearDepth
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glClearDepth
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glDeleteLists
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glDeleteLists
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glDeleteTextures
 * Signature: (ILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glDeleteTextures
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glCullFace
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glCullFace
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glCopyTexSubImage2D
 * Signature: (IIIIIIII)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glCopyTexSubImage2D
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glCopyTexSubImage1D
 * Signature: (IIIIII)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glCopyTexSubImage1D
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glCopyTexImage2D
 * Signature: (IIIIIIII)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glCopyTexImage2D
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glCopyTexImage1D
 * Signature: (IIIIIII)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glCopyTexImage1D
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glCopyPixels
 * Signature: (IIIII)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glCopyPixels
  (JNIEnv *, jclass, jint, jint, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glColorPointer
 * Signature: (IIILjava/nio/Buffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glColorPointer
  (JNIEnv *, jclass, jint, jint, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glColorMaterial
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glColorMaterial
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glColorMask
 * Signature: (ZZZZ)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glColorMask
  (JNIEnv *, jclass, jboolean, jboolean, jboolean, jboolean);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glColor3b
 * Signature: (BBB)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glColor3b
  (JNIEnv *, jclass, jbyte, jbyte, jbyte);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glColor3d
 * Signature: (DDD)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glColor3d
  (JNIEnv *, jclass, jdouble, jdouble, jdouble);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glColor3f
 * Signature: (FFF)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glColor3f
  (JNIEnv *, jclass, jfloat, jfloat, jfloat);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glColor3i
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glColor3i
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glColor3s
 * Signature: (SSS)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glColor3s
  (JNIEnv *, jclass, jshort, jshort, jshort);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glColor3ub
 * Signature: (BBB)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glColor3ub
  (JNIEnv *, jclass, jbyte, jbyte, jbyte);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glColor3ui
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glColor3ui
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glColor3us
 * Signature: (SSS)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glColor3us
  (JNIEnv *, jclass, jshort, jshort, jshort);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glColor4b
 * Signature: (BBBB)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glColor4b
  (JNIEnv *, jclass, jbyte, jbyte, jbyte, jbyte);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glColor4d
 * Signature: (DDDD)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glColor4d
  (JNIEnv *, jclass, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glColor4f
 * Signature: (FFFF)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glColor4f
  (JNIEnv *, jclass, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glColor4i
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glColor4i
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glColor4s
 * Signature: (SSSS)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glColor4s
  (JNIEnv *, jclass, jshort, jshort, jshort, jshort);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glColor4ub
 * Signature: (BBBB)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glColor4ub
  (JNIEnv *, jclass, jbyte, jbyte, jbyte, jbyte);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glColor4ui
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glColor4ui
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glColor4us
 * Signature: (SSSS)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glColor4us
  (JNIEnv *, jclass, jshort, jshort, jshort, jshort);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glClipPlane
 * Signature: (ILjava/nio/DoubleBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glClipPlane
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glClearStencil
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glClearStencil
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glClearIndex
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glClearIndex
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glEvalPoint1
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glEvalPoint1
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glEvalPoint2
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glEvalPoint2
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glEvalMesh1
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glEvalMesh1
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glEvalMesh2
 * Signature: (IIIII)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glEvalMesh2
  (JNIEnv *, jclass, jint, jint, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glEvalCoord1d
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glEvalCoord1d
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glEvalCoord1f
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glEvalCoord1f
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glEvalCoord2d
 * Signature: (DD)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glEvalCoord2d
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glEvalCoord2f
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glEvalCoord2f
  (JNIEnv *, jclass, jfloat, jfloat);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glEnableClientState
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glEnableClientState
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glDisableClientState
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glDisableClientState
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glEnable
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glEnable
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glDisable
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glDisable
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glEdgeFlagPointer
 * Signature: (ILjava/nio/Buffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glEdgeFlagPointer
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glEdgeFlag
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glEdgeFlag
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glDrawPixels
 * Signature: (IIIILjava/nio/Buffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glDrawPixels
  (JNIEnv *, jclass, jint, jint, jint, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glDrawElements
 * Signature: (IIILjava/nio/Buffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glDrawElements
  (JNIEnv *, jclass, jint, jint, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glDrawBuffer
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glDrawBuffer
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glDrawArrays
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glDrawArrays
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glDepthRange
 * Signature: (DD)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glDepthRange
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glDepthMask
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glDepthMask
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glDepthFunc
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glDepthFunc
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glFeedbackBuffer
 * Signature: (IILjava/nio/FloatBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glFeedbackBuffer
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glGetPixelMapfv
 * Signature: (ILjava/nio/FloatBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glGetPixelMapfv
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glGetPixelMapuiv
 * Signature: (ILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glGetPixelMapuiv
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glGetPixelMapusv
 * Signature: (ILjava/nio/CharBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glGetPixelMapusv
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glGetMaterialfv
 * Signature: (IILjava/nio/FloatBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glGetMaterialfv
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glGetMaterialiv
 * Signature: (IILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glGetMaterialiv
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glGetMapdv
 * Signature: (IILjava/nio/DoubleBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glGetMapdv
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glGetMapfv
 * Signature: (IILjava/nio/FloatBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glGetMapfv
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glGetMapiv
 * Signature: (IILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glGetMapiv
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glGetLightfv
 * Signature: (IILjava/nio/FloatBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glGetLightfv
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glGetLightiv
 * Signature: (IILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glGetLightiv
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glGetError
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_lwjgl_opengl_CoreGL11_glGetError
  (JNIEnv *, jclass);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glGetClipPlane
 * Signature: (ILjava/nio/DoubleBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glGetClipPlane
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glGetBooleanv
 * Signature: (ILjava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glGetBooleanv
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glGetDoublev
 * Signature: (ILjava/nio/DoubleBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glGetDoublev
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glGetFloatv
 * Signature: (ILjava/nio/FloatBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glGetFloatv
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glGetIntegerv
 * Signature: (ILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glGetIntegerv
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glGenTextures
 * Signature: (ILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glGenTextures
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glGenLists
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_lwjgl_opengl_CoreGL11_glGenLists
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glFrustum
 * Signature: (DDDDDD)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glFrustum
  (JNIEnv *, jclass, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glFrontFace
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glFrontFace
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glFogf
 * Signature: (IF)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glFogf
  (JNIEnv *, jclass, jint, jfloat);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glFogi
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glFogi
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glFogfv
 * Signature: (ILjava/nio/FloatBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glFogfv
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glFogiv
 * Signature: (ILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glFogiv
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glFlush
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glFlush
  (JNIEnv *, jclass);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glFinish
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glFinish
  (JNIEnv *, jclass);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glGetPointerv
 * Signature: (II)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_org_lwjgl_opengl_CoreGL11_glGetPointerv
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glIsEnabled
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_lwjgl_opengl_CoreGL11_glIsEnabled
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glInterleavedArrays
 * Signature: (IILjava/nio/Buffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glInterleavedArrays
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glInitNames
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glInitNames
  (JNIEnv *, jclass);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glIndexPointer
 * Signature: (IILjava/nio/Buffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glIndexPointer
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glIndexMask
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glIndexMask
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glIndexd
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glIndexd
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glIndexf
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glIndexf
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glIndexi
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glIndexi
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glIndexs
 * Signature: (S)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glIndexs
  (JNIEnv *, jclass, jshort);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glIndexub
 * Signature: (B)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glIndexub
  (JNIEnv *, jclass, jbyte);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glHint
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glHint
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glGetTexParameterfv
 * Signature: (IILjava/nio/FloatBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glGetTexParameterfv
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glGetTexParameteriv
 * Signature: (IILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glGetTexParameteriv
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glGetTexLevelParameterfv
 * Signature: (IIILjava/nio/FloatBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glGetTexLevelParameterfv
  (JNIEnv *, jclass, jint, jint, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glGetTexLevelParameteriv
 * Signature: (IIILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glGetTexLevelParameteriv
  (JNIEnv *, jclass, jint, jint, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glGetTexImage
 * Signature: (IIIILjava/nio/Buffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glGetTexImage
  (JNIEnv *, jclass, jint, jint, jint, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glGetTexGendv
 * Signature: (IILjava/nio/DoubleBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glGetTexGendv
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glGetTexGenfv
 * Signature: (IILjava/nio/FloatBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glGetTexGenfv
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glGetTexGeniv
 * Signature: (IILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glGetTexGeniv
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glGetTexEnvfv
 * Signature: (IILjava/nio/FloatBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glGetTexEnvfv
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glGetTexEnviv
 * Signature: (IILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glGetTexEnviv
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glGetString
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_lwjgl_opengl_CoreGL11_glGetString
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glGetPolygonStipple
 * Signature: (Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glGetPolygonStipple
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glIsList
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_lwjgl_opengl_CoreGL11_glIsList
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glMaterialf
 * Signature: (IIF)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glMaterialf
  (JNIEnv *, jclass, jint, jint, jfloat);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glMateriali
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glMateriali
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glMaterialfv
 * Signature: (IILjava/nio/FloatBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glMaterialfv
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glMaterialiv
 * Signature: (IILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glMaterialiv
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glMapGrid1d
 * Signature: (IDD)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glMapGrid1d
  (JNIEnv *, jclass, jint, jdouble, jdouble);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glMapGrid1f
 * Signature: (IFF)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glMapGrid1f
  (JNIEnv *, jclass, jint, jfloat, jfloat);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glMapGrid2d
 * Signature: (IDDIDD)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glMapGrid2d
  (JNIEnv *, jclass, jint, jdouble, jdouble, jint, jdouble, jdouble);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glMapGrid2f
 * Signature: (IFFIFF)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glMapGrid2f
  (JNIEnv *, jclass, jint, jfloat, jfloat, jint, jfloat, jfloat);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glMap2d
 * Signature: (IDDIIDDIILjava/nio/DoubleBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glMap2d
  (JNIEnv *, jclass, jint, jdouble, jdouble, jint, jint, jdouble, jdouble, jint, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glMap2f
 * Signature: (IFFIIFFIILjava/nio/FloatBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glMap2f
  (JNIEnv *, jclass, jint, jfloat, jfloat, jint, jint, jfloat, jfloat, jint, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glMap1d
 * Signature: (IDDIILjava/nio/DoubleBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glMap1d
  (JNIEnv *, jclass, jint, jdouble, jdouble, jint, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glMap1f
 * Signature: (IFFIILjava/nio/FloatBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glMap1f
  (JNIEnv *, jclass, jint, jfloat, jfloat, jint, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glLogicOp
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glLogicOp
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glLoadName
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glLoadName
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glLoadMatrixd
 * Signature: (Ljava/nio/DoubleBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glLoadMatrixd
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glLoadMatrixf
 * Signature: (Ljava/nio/FloatBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glLoadMatrixf
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glLoadIdentity
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glLoadIdentity
  (JNIEnv *, jclass);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glListBase
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glListBase
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glLineWidth
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glLineWidth
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glLineStipple
 * Signature: (IS)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glLineStipple
  (JNIEnv *, jclass, jint, jshort);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glLightModelf
 * Signature: (IF)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glLightModelf
  (JNIEnv *, jclass, jint, jfloat);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glLightModeli
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glLightModeli
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glLightModelfv
 * Signature: (ILjava/nio/FloatBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glLightModelfv
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glLightModeliv
 * Signature: (ILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glLightModeliv
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glLightf
 * Signature: (IIF)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glLightf
  (JNIEnv *, jclass, jint, jint, jfloat);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glLighti
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glLighti
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glLightfv
 * Signature: (IILjava/nio/FloatBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glLightfv
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glLightiv
 * Signature: (IILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glLightiv
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glIsTexture
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_lwjgl_opengl_CoreGL11_glIsTexture
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glMatrixMode
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glMatrixMode
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glPolygonStipple
 * Signature: (Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glPolygonStipple
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glPolygonOffset
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glPolygonOffset
  (JNIEnv *, jclass, jfloat, jfloat);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glPolygonMode
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glPolygonMode
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glPointSize
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glPointSize
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glPixelZoom
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glPixelZoom
  (JNIEnv *, jclass, jfloat, jfloat);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glPixelTransferf
 * Signature: (IF)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glPixelTransferf
  (JNIEnv *, jclass, jint, jfloat);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glPixelTransferi
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glPixelTransferi
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glPixelStoref
 * Signature: (IF)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glPixelStoref
  (JNIEnv *, jclass, jint, jfloat);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glPixelStorei
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glPixelStorei
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glPixelMapfv
 * Signature: (IILjava/nio/FloatBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glPixelMapfv
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glPixelMapuiv
 * Signature: (IILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glPixelMapuiv
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glPixelMapusv
 * Signature: (IILjava/nio/CharBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glPixelMapusv
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glPassThrough
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glPassThrough
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glOrtho
 * Signature: (DDDDDD)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glOrtho
  (JNIEnv *, jclass, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glNormalPointer
 * Signature: (IILjava/nio/Buffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glNormalPointer
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glNormal3b
 * Signature: (BBB)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glNormal3b
  (JNIEnv *, jclass, jbyte, jbyte, jbyte);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glNormal3d
 * Signature: (DDD)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glNormal3d
  (JNIEnv *, jclass, jdouble, jdouble, jdouble);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glNormal3f
 * Signature: (FFF)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glNormal3f
  (JNIEnv *, jclass, jfloat, jfloat, jfloat);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glNormal3i
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glNormal3i
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glNormal3s
 * Signature: (SSS)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glNormal3s
  (JNIEnv *, jclass, jshort, jshort, jshort);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glNewList
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glNewList
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glEndList
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glEndList
  (JNIEnv *, jclass);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glMultMatrixd
 * Signature: (Ljava/nio/DoubleBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glMultMatrixd
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glMultMatrixf
 * Signature: (Ljava/nio/FloatBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glMultMatrixf
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glPrioritizeTextures
 * Signature: (ILjava/nio/IntBuffer;Ljava/nio/FloatBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glPrioritizeTextures
  (JNIEnv *, jclass, jint, jobject, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glShadeModel
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glShadeModel
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glSelectBuffer
 * Signature: (ILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glSelectBuffer
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glScissor
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glScissor
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glScaled
 * Signature: (DDD)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glScaled
  (JNIEnv *, jclass, jdouble, jdouble, jdouble);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glScalef
 * Signature: (FFF)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glScalef
  (JNIEnv *, jclass, jfloat, jfloat, jfloat);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glRotated
 * Signature: (DDDD)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glRotated
  (JNIEnv *, jclass, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glRotatef
 * Signature: (FFFF)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glRotatef
  (JNIEnv *, jclass, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glRenderMode
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_lwjgl_opengl_CoreGL11_glRenderMode
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glRectd
 * Signature: (DDDD)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glRectd
  (JNIEnv *, jclass, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glRectf
 * Signature: (FFFF)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glRectf
  (JNIEnv *, jclass, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glRecti
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glRecti
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glRects
 * Signature: (SSSS)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glRects
  (JNIEnv *, jclass, jshort, jshort, jshort, jshort);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glReadPixels
 * Signature: (IIIIIILjava/nio/Buffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glReadPixels
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glReadBuffer
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glReadBuffer
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glRasterPos2d
 * Signature: (DD)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glRasterPos2d
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glRasterPos2f
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glRasterPos2f
  (JNIEnv *, jclass, jfloat, jfloat);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glRasterPos2i
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glRasterPos2i
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glRasterPos2s
 * Signature: (SS)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glRasterPos2s
  (JNIEnv *, jclass, jshort, jshort);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glRasterPos3d
 * Signature: (DDD)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glRasterPos3d
  (JNIEnv *, jclass, jdouble, jdouble, jdouble);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glRasterPos3f
 * Signature: (FFF)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glRasterPos3f
  (JNIEnv *, jclass, jfloat, jfloat, jfloat);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glRasterPos3i
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glRasterPos3i
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glRasterPos3s
 * Signature: (SSS)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glRasterPos3s
  (JNIEnv *, jclass, jshort, jshort, jshort);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glRasterPos4d
 * Signature: (DDDD)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glRasterPos4d
  (JNIEnv *, jclass, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glRasterPos4f
 * Signature: (FFFF)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glRasterPos4f
  (JNIEnv *, jclass, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glRasterPos4i
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glRasterPos4i
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glRasterPos4s
 * Signature: (SSSS)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glRasterPos4s
  (JNIEnv *, jclass, jshort, jshort, jshort, jshort);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glPushName
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glPushName
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glPopName
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glPopName
  (JNIEnv *, jclass);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glPushMatrix
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glPushMatrix
  (JNIEnv *, jclass);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glPopMatrix
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glPopMatrix
  (JNIEnv *, jclass);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glPushClientAttrib
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glPushClientAttrib
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glPopClientAttrib
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glPopClientAttrib
  (JNIEnv *, jclass);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glPushAttrib
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glPushAttrib
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glPopAttrib
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glPopAttrib
  (JNIEnv *, jclass);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glStencilFunc
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glStencilFunc
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glVertexPointer
 * Signature: (IIILjava/nio/Buffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glVertexPointer
  (JNIEnv *, jclass, jint, jint, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glVertex2d
 * Signature: (DD)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glVertex2d
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glVertex2f
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glVertex2f
  (JNIEnv *, jclass, jfloat, jfloat);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glVertex2i
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glVertex2i
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glVertex2s
 * Signature: (SS)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glVertex2s
  (JNIEnv *, jclass, jshort, jshort);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glVertex3d
 * Signature: (DDD)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glVertex3d
  (JNIEnv *, jclass, jdouble, jdouble, jdouble);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glVertex3f
 * Signature: (FFF)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glVertex3f
  (JNIEnv *, jclass, jfloat, jfloat, jfloat);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glVertex3i
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glVertex3i
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glVertex3s
 * Signature: (SSS)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glVertex3s
  (JNIEnv *, jclass, jshort, jshort, jshort);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glVertex4d
 * Signature: (DDDD)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glVertex4d
  (JNIEnv *, jclass, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glVertex4f
 * Signature: (FFFF)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glVertex4f
  (JNIEnv *, jclass, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glVertex4i
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glVertex4i
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glVertex4s
 * Signature: (SSSS)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glVertex4s
  (JNIEnv *, jclass, jshort, jshort, jshort, jshort);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glTranslated
 * Signature: (DDD)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glTranslated
  (JNIEnv *, jclass, jdouble, jdouble, jdouble);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glTranslatef
 * Signature: (FFF)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glTranslatef
  (JNIEnv *, jclass, jfloat, jfloat, jfloat);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glTexSubImage2D
 * Signature: (IIIIIIIILjava/nio/Buffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glTexSubImage2D
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jint, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glTexSubImage1D
 * Signature: (IIIIIILjava/nio/Buffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glTexSubImage1D
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glTexParameterf
 * Signature: (IIF)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glTexParameterf
  (JNIEnv *, jclass, jint, jint, jfloat);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glTexParameteri
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glTexParameteri
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glTexImage2D
 * Signature: (IIIIIIIILjava/nio/Buffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glTexImage2D
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jint, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glTexImage1D
 * Signature: (IIIIIIILjava/nio/Buffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glTexImage1D
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glTexGend
 * Signature: (IID)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glTexGend
  (JNIEnv *, jclass, jint, jint, jdouble);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glTexGenf
 * Signature: (IIF)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glTexGenf
  (JNIEnv *, jclass, jint, jint, jfloat);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glTexGeni
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glTexGeni
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glTexGendv
 * Signature: (IILjava/nio/DoubleBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glTexGendv
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glTexGenfv
 * Signature: (IILjava/nio/FloatBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glTexGenfv
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glTexGeniv
 * Signature: (IILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glTexGeniv
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glTexEnvf
 * Signature: (IIF)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glTexEnvf
  (JNIEnv *, jclass, jint, jint, jfloat);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glTexEnvi
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glTexEnvi
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glTexEnvfv
 * Signature: (IILjava/nio/FloatBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glTexEnvfv
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glTexEnviv
 * Signature: (IILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glTexEnviv
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glTexCoordPointer
 * Signature: (IIILjava/nio/Buffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glTexCoordPointer
  (JNIEnv *, jclass, jint, jint, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glTexCoord1d
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glTexCoord1d
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glTexCoord1f
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glTexCoord1f
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glTexCoord1i
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glTexCoord1i
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glTexCoord1s
 * Signature: (S)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glTexCoord1s
  (JNIEnv *, jclass, jshort);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glTexCoord2d
 * Signature: (DD)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glTexCoord2d
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glTexCoord2f
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glTexCoord2f
  (JNIEnv *, jclass, jfloat, jfloat);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glTexCoord2i
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glTexCoord2i
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glTexCoord2s
 * Signature: (SS)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glTexCoord2s
  (JNIEnv *, jclass, jshort, jshort);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glTexCoord3d
 * Signature: (DDD)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glTexCoord3d
  (JNIEnv *, jclass, jdouble, jdouble, jdouble);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glTexCoord3f
 * Signature: (FFF)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glTexCoord3f
  (JNIEnv *, jclass, jfloat, jfloat, jfloat);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glTexCoord3i
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glTexCoord3i
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glTexCoord3s
 * Signature: (SSS)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glTexCoord3s
  (JNIEnv *, jclass, jshort, jshort, jshort);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glTexCoord4d
 * Signature: (DDDD)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glTexCoord4d
  (JNIEnv *, jclass, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glTexCoord4f
 * Signature: (FFFF)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glTexCoord4f
  (JNIEnv *, jclass, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glTexCoord4i
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glTexCoord4i
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glTexCoord4s
 * Signature: (SSSS)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glTexCoord4s
  (JNIEnv *, jclass, jshort, jshort, jshort, jshort);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glStencilOp
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glStencilOp
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glStencilMask
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glStencilMask
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL11
 * Method:    glViewport
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL11_glViewport
  (JNIEnv *, jclass, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
