/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_lwjgl_Math_MatrixOpNormalise_MatrixOpDirect */

#ifndef _Included_org_lwjgl_Math_MatrixOpNormalise_MatrixOpDirect
#define _Included_org_lwjgl_Math_MatrixOpNormalise_MatrixOpDirect
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_lwjgl_Math_MatrixOpNormalise_MatrixOpDirect
 * Method:    execute
 * Signature: (IIIIIZIIZ)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_Math_00024MatrixOpNormalise_00024MatrixOpDirect_execute
  (JNIEnv *, jobject, jint, jint, jint, jint, jint, jboolean, jint, jint, jboolean);

#ifdef __cplusplus
}
#endif
#endif
