/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_lwjgl_openal_AL */

#ifndef _Included_org_lwjgl_openal_AL
#define _Included_org_lwjgl_openal_AL
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: alc */
/* Inaccessible static: device */
/* Inaccessible static: context */
/* Inaccessible static: deviceArguments */
/* Inaccessible static: contextFrequency */
/* Inaccessible static: contextRefresh */
/* Inaccessible static: contextSynchronized */
/* Inaccessible static: created */
/* Inaccessible static: class_000240 */
/* Inaccessible static: class_000241 */
/*
 * Class:     org_lwjgl_openal_AL
 * Method:    nCreate
 * Signature: ([Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_openal_AL_nCreate
  (JNIEnv *, jclass, jobjectArray);

/*
 * Class:     org_lwjgl_openal_AL
 * Method:    nDestroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_openal_AL_nDestroy
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
