/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_lwjgl_opengl_CoreGL14 */

#ifndef _Included_org_lwjgl_opengl_CoreGL14
#define _Included_org_lwjgl_opengl_CoreGL14
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_lwjgl_opengl_CoreGL14
 * Method:    glMultiDrawArrays
 * Signature: (ILjava/nio/IntBuffer;Ljava/nio/IntBuffer;I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL14_glMultiDrawArrays
  (JNIEnv *, jclass, jint, jobject, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
