/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_lwjgl_input_Joystick */

#ifndef _Included_org_lwjgl_input_Joystick
#define _Included_org_lwjgl_input_Joystick
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: _00024assertionsDisabled */
#undef org_lwjgl_input_Joystick_POV_CENTER
#define org_lwjgl_input_Joystick_POV_CENTER -1L
#undef org_lwjgl_input_Joystick_POV_NORTH
#define org_lwjgl_input_Joystick_POV_NORTH 0L
#undef org_lwjgl_input_Joystick_POV_SOUTH
#define org_lwjgl_input_Joystick_POV_SOUTH 18000L
#undef org_lwjgl_input_Joystick_POV_EAST
#define org_lwjgl_input_Joystick_POV_EAST 27000L
#undef org_lwjgl_input_Joystick_POV_WEST
#define org_lwjgl_input_Joystick_POV_WEST 9000L
/* Inaccessible static: class_00024org_00024lwjgl_00024input_00024Joystick */
/*
 * Class:     org_lwjgl_input_Joystick
 * Method:    nPoll
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_input_Joystick_nPoll
  (JNIEnv *, jobject);

/*
 * Class:     org_lwjgl_input_Joystick
 * Method:    nCreate
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_lwjgl_input_Joystick_nCreate
  (JNIEnv *, jobject);

/*
 * Class:     org_lwjgl_input_Joystick
 * Method:    nDestroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_input_Joystick_nDestroy
  (JNIEnv *, jobject);

/*
 * Class:     org_lwjgl_input_Joystick
 * Method:    initIDs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_input_Joystick_initIDs
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
