/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_lwjgl_opengl_GL12 */

#ifndef _Included_org_lwjgl_opengl_GL12
#define _Included_org_lwjgl_opengl_GL12
#ifdef __cplusplus
extern "C" {
#endif
#undef org_lwjgl_opengl_GL12_GL_PACK_SKIP_IMAGES
#define org_lwjgl_opengl_GL12_GL_PACK_SKIP_IMAGES 32875L
#undef org_lwjgl_opengl_GL12_GL_PACK_IMAGE_HEIGHT
#define org_lwjgl_opengl_GL12_GL_PACK_IMAGE_HEIGHT 32876L
#undef org_lwjgl_opengl_GL12_GL_UNPACK_SKIP_IMAGES
#define org_lwjgl_opengl_GL12_GL_UNPACK_SKIP_IMAGES 32877L
#undef org_lwjgl_opengl_GL12_GL_UNPACK_IMAGE_HEIGHT
#define org_lwjgl_opengl_GL12_GL_UNPACK_IMAGE_HEIGHT 32878L
#undef org_lwjgl_opengl_GL12_GL_TEXTURE_3D
#define org_lwjgl_opengl_GL12_GL_TEXTURE_3D 32879L
#undef org_lwjgl_opengl_GL12_GL_PROXY_TEXTURE_3D
#define org_lwjgl_opengl_GL12_GL_PROXY_TEXTURE_3D 32880L
#undef org_lwjgl_opengl_GL12_GL_TEXTURE_DEPTH
#define org_lwjgl_opengl_GL12_GL_TEXTURE_DEPTH 32881L
#undef org_lwjgl_opengl_GL12_GL_TEXTURE_WRAP_R
#define org_lwjgl_opengl_GL12_GL_TEXTURE_WRAP_R 32882L
#undef org_lwjgl_opengl_GL12_GL_MAX_3D_TEXTURE_SIZE
#define org_lwjgl_opengl_GL12_GL_MAX_3D_TEXTURE_SIZE 32883L
#undef org_lwjgl_opengl_GL12_GL_BGR
#define org_lwjgl_opengl_GL12_GL_BGR 32992L
#undef org_lwjgl_opengl_GL12_GL_BGRA
#define org_lwjgl_opengl_GL12_GL_BGRA 32993L
#undef org_lwjgl_opengl_GL12_GL_UNSIGNED_BYTE_3_3_2
#define org_lwjgl_opengl_GL12_GL_UNSIGNED_BYTE_3_3_2 32818L
#undef org_lwjgl_opengl_GL12_GL_UNSIGNED_BYTE_2_3_3_REV
#define org_lwjgl_opengl_GL12_GL_UNSIGNED_BYTE_2_3_3_REV 33634L
#undef org_lwjgl_opengl_GL12_GL_UNSIGNED_SHORT_5_6_5
#define org_lwjgl_opengl_GL12_GL_UNSIGNED_SHORT_5_6_5 33635L
#undef org_lwjgl_opengl_GL12_GL_UNSIGNED_SHORT_5_6_5_REV
#define org_lwjgl_opengl_GL12_GL_UNSIGNED_SHORT_5_6_5_REV 33636L
#undef org_lwjgl_opengl_GL12_GL_UNSIGNED_SHORT_4_4_4_4
#define org_lwjgl_opengl_GL12_GL_UNSIGNED_SHORT_4_4_4_4 32819L
#undef org_lwjgl_opengl_GL12_GL_UNSIGNED_SHORT_4_4_4_4_REV
#define org_lwjgl_opengl_GL12_GL_UNSIGNED_SHORT_4_4_4_4_REV 33637L
#undef org_lwjgl_opengl_GL12_GL_UNSIGNED_SHORT_5_5_5_1
#define org_lwjgl_opengl_GL12_GL_UNSIGNED_SHORT_5_5_5_1 32820L
#undef org_lwjgl_opengl_GL12_GL_UNSIGNED_SHORT_1_5_5_5_REV
#define org_lwjgl_opengl_GL12_GL_UNSIGNED_SHORT_1_5_5_5_REV 33638L
#undef org_lwjgl_opengl_GL12_GL_UNSIGNED_INT_8_8_8_8
#define org_lwjgl_opengl_GL12_GL_UNSIGNED_INT_8_8_8_8 32821L
#undef org_lwjgl_opengl_GL12_GL_UNSIGNED_INT_8_8_8_8_REV
#define org_lwjgl_opengl_GL12_GL_UNSIGNED_INT_8_8_8_8_REV 33639L
#undef org_lwjgl_opengl_GL12_GL_UNSIGNED_INT_10_10_10_2
#define org_lwjgl_opengl_GL12_GL_UNSIGNED_INT_10_10_10_2 32822L
#undef org_lwjgl_opengl_GL12_GL_UNSIGNED_INT_2_10_10_10_REV
#define org_lwjgl_opengl_GL12_GL_UNSIGNED_INT_2_10_10_10_REV 33640L
#undef org_lwjgl_opengl_GL12_GL_RESCALE_NORMAL
#define org_lwjgl_opengl_GL12_GL_RESCALE_NORMAL 32826L
#undef org_lwjgl_opengl_GL12_GL_LIGHT_MODEL_COLOR_CONTROL
#define org_lwjgl_opengl_GL12_GL_LIGHT_MODEL_COLOR_CONTROL 33272L
#undef org_lwjgl_opengl_GL12_GL_SINGLE_COLOR
#define org_lwjgl_opengl_GL12_GL_SINGLE_COLOR 33273L
#undef org_lwjgl_opengl_GL12_GL_SEPARATE_SPECULAR_COLOR
#define org_lwjgl_opengl_GL12_GL_SEPARATE_SPECULAR_COLOR 33274L
#undef org_lwjgl_opengl_GL12_GL_CLAMP_TO_EDGE
#define org_lwjgl_opengl_GL12_GL_CLAMP_TO_EDGE 33071L
#undef org_lwjgl_opengl_GL12_GL_TEXTURE_MIN_LOD
#define org_lwjgl_opengl_GL12_GL_TEXTURE_MIN_LOD 33082L
#undef org_lwjgl_opengl_GL12_GL_TEXTURE_MAX_LOD
#define org_lwjgl_opengl_GL12_GL_TEXTURE_MAX_LOD 33083L
#undef org_lwjgl_opengl_GL12_GL_TEXTURE_BASE_LEVEL
#define org_lwjgl_opengl_GL12_GL_TEXTURE_BASE_LEVEL 33084L
#undef org_lwjgl_opengl_GL12_GL_TEXTURE_MAX_LEVEL
#define org_lwjgl_opengl_GL12_GL_TEXTURE_MAX_LEVEL 33085L
#undef org_lwjgl_opengl_GL12_GL_MAX_ELEMENTS_VERTICES
#define org_lwjgl_opengl_GL12_GL_MAX_ELEMENTS_VERTICES 33000L
#undef org_lwjgl_opengl_GL12_GL_MAX_ELEMENTS_INDICES
#define org_lwjgl_opengl_GL12_GL_MAX_ELEMENTS_INDICES 33001L
#undef org_lwjgl_opengl_GL12_GL_ALIASED_POINT_SIZE_RANGE
#define org_lwjgl_opengl_GL12_GL_ALIASED_POINT_SIZE_RANGE 33901L
#undef org_lwjgl_opengl_GL12_GL_ALIASED_LINE_WIDTH_RANGE
#define org_lwjgl_opengl_GL12_GL_ALIASED_LINE_WIDTH_RANGE 33902L
/*
 * Class:     org_lwjgl_opengl_GL12
 * Method:    nglDrawRangeElements
 * Signature: (IIIIILjava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL12_nglDrawRangeElements
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_GL12
 * Method:    nglDrawRangeElementsVBO
 * Signature: (IIIIII)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL12_nglDrawRangeElementsVBO
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_GL12
 * Method:    nglTexImage3D
 * Signature: (IIIIIIIIILjava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL12_nglTexImage3D
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jint, jint, jint, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_GL12
 * Method:    nglTexSubImage3D
 * Signature: (IIIIIIIIIILjava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL12_nglTexSubImage3D
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_GL12
 * Method:    glCopyTexSubImage3D
 * Signature: (IIIIIIIII)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL12_glCopyTexSubImage3D
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
