/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_lwjgl_opengl_GL */

#ifndef _Included_org_lwjgl_opengl_GL
#define _Included_org_lwjgl_opengl_GL
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: _00024assertionsDisabled */
/* Inaccessible static: class_00024org_00024lwjgl_00024opengl_00024CoreGL11 */
/* Inaccessible static: _00024assertionsDisabled */
/* Inaccessible static: class_00024org_00024lwjgl_00024opengl_00024CoreGL12 */
/* Inaccessible static: _00024assertionsDisabled */
/* Inaccessible static: class_00024org_00024lwjgl_00024opengl_00024CoreGL14 */
/* Inaccessible static: _00024assertionsDisabled */
/* Inaccessible static: class_00024org_00024lwjgl_00024opengl_00024GL */
/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    glActiveStencilFaceEXT
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_glActiveStencilFaceEXT
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    glActiveTextureARB
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_glActiveTextureARB
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    glAlphaFragmentOp1ATI
 * Signature: (IIIIII)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_glAlphaFragmentOp1ATI
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    glAlphaFragmentOp2ATI
 * Signature: (IIIIIIIII)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_glAlphaFragmentOp2ATI
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    glAlphaFragmentOp3ATI
 * Signature: (IIIIIIIIIIII)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_glAlphaFragmentOp3ATI
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    nglAreProgramsResidentNV
 * Signature: (ILjava/nio/IntBuffer;ILjava/nio/ByteBuffer;I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_lwjgl_opengl_GL_nglAreProgramsResidentNV
  (JNIEnv *, jclass, jint, jobject, jint, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    glArrayObjectATI
 * Signature: (IIIIII)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_glArrayObjectATI
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    glBeginFragmentShaderATI
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_glBeginFragmentShaderATI
  (JNIEnv *, jclass);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    glBeginOcclusionQueryNV
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_glBeginOcclusionQueryNV
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    glBeginVertexShaderEXT
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_glBeginVertexShaderEXT
  (JNIEnv *, jclass);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    glBindFragmentShaderATI
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_glBindFragmentShaderATI
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    glBindLightParameterEXT
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_org_lwjgl_opengl_GL_glBindLightParameterEXT
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    glBindMaterialParameterEXT
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_org_lwjgl_opengl_GL_glBindMaterialParameterEXT
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    glBindParameterEXT
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_lwjgl_opengl_GL_glBindParameterEXT
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    glBindProgramARB
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_glBindProgramARB
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    glBindProgramNV
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_glBindProgramNV
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    glBindTexGenParameterEXT
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_org_lwjgl_opengl_GL_glBindTexGenParameterEXT
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    glBindTextureUnitParameterEXT
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_org_lwjgl_opengl_GL_glBindTextureUnitParameterEXT
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    glBindVertexShaderEXT
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_glBindVertexShaderEXT
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    glClientActiveTextureARB
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_glClientActiveTextureARB
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    glClientActiveVertexStreamATI
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_glClientActiveVertexStreamATI
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    glColorFragmentOp1ATI
 * Signature: (IIIIIII)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_glColorFragmentOp1ATI
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    glColorFragmentOp2ATI
 * Signature: (IIIIIIIIII)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_glColorFragmentOp2ATI
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    glColorFragmentOp3ATI
 * Signature: (IIIIIIIIIIIII)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_glColorFragmentOp3ATI
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    glCombinerInputNV
 * Signature: (IIIIII)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_glCombinerInputNV
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    glCombinerOutputNV
 * Signature: (IIIIIIIZZZ)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_glCombinerOutputNV
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jint, jboolean, jboolean, jboolean);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    glCombinerParameterfNV
 * Signature: (IF)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_glCombinerParameterfNV
  (JNIEnv *, jclass, jint, jfloat);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    nglCombinerParameterfvNV
 * Signature: (ILjava/nio/FloatBuffer;I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_nglCombinerParameterfvNV
  (JNIEnv *, jclass, jint, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    glCombinerParameteriNV
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_glCombinerParameteriNV
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    nglCombinerParameterivNV
 * Signature: (ILjava/nio/IntBuffer;I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_nglCombinerParameterivNV
  (JNIEnv *, jclass, jint, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    nglCombinerStageParameterfvNV
 * Signature: (IILjava/nio/FloatBuffer;I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_nglCombinerStageParameterfvNV
  (JNIEnv *, jclass, jint, jint, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    nglCompressedTexImage1DARB
 * Signature: (IIIIIILjava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_nglCompressedTexImage1DARB
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    nglCompressedTexImage2DARB
 * Signature: (IIIIIIILjava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_nglCompressedTexImage2DARB
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jint, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    nglCompressedTexImage3DARB
 * Signature: (IIIIIIIILjava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_nglCompressedTexImage3DARB
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jint, jint, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    nglCompressedTexSubImage1DARB
 * Signature: (IIIIIILjava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_nglCompressedTexSubImage1DARB
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    nglCompressedTexSubImage2DARB
 * Signature: (IIIIIIIILjava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_nglCompressedTexSubImage2DARB
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jint, jint, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    nglCompressedTexSubImage3DARB
 * Signature: (IIIIIIIIIILjava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_nglCompressedTexSubImage3DARB
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    glCurrentPaletteMatrixARB
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_glCurrentPaletteMatrixARB
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    nglDeleteFencesNV
 * Signature: (ILjava/nio/IntBuffer;I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_nglDeleteFencesNV
  (JNIEnv *, jclass, jint, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    glDeleteFragmentShaderATI
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_glDeleteFragmentShaderATI
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    nglDeleteOcclusionQueriesNV
 * Signature: (ILjava/nio/IntBuffer;I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_nglDeleteOcclusionQueriesNV
  (JNIEnv *, jclass, jint, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    nglDeleteProgramsARB
 * Signature: (ILjava/nio/IntBuffer;I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_nglDeleteProgramsARB
  (JNIEnv *, jclass, jint, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    nglDeleteProgramsNV
 * Signature: (ILjava/nio/IntBuffer;I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_nglDeleteProgramsNV
  (JNIEnv *, jclass, jint, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    glDeleteVertexShaderEXT
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_glDeleteVertexShaderEXT
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    glDisableVariantClientStateEXT
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_glDisableVariantClientStateEXT
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    glDisableVertexAttribArrayARB
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_glDisableVertexAttribArrayARB
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    glDrawElementArrayATI
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_glDrawElementArrayATI
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    glDrawRangeElementArrayATI
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_glDrawRangeElementArrayATI
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    nglDrawRangeElementsEXT
 * Signature: (IIIIILjava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_nglDrawRangeElementsEXT
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    nglElementPointerATI
 * Signature: (ILjava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_nglElementPointerATI
  (JNIEnv *, jclass, jint, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    glEnableVariantClientStateEXT
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_glEnableVariantClientStateEXT
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    glEnableVertexAttribArrayARB
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_glEnableVertexAttribArrayARB
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    glEndFragmentShaderATI
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_glEndFragmentShaderATI
  (JNIEnv *, jclass);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    glEndOcclusionQueryNV
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_glEndOcclusionQueryNV
  (JNIEnv *, jclass);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    glEndVertexShaderEXT
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_glEndVertexShaderEXT
  (JNIEnv *, jclass);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    glEvalMapsNV
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_glEvalMapsNV
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    nglExecuteProgramNV
 * Signature: (IILjava/nio/FloatBuffer;I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_nglExecuteProgramNV
  (JNIEnv *, jclass, jint, jint, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    glExtractComponentEXT
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_glExtractComponentEXT
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    glFinalCombinerInputNV
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_glFinalCombinerInputNV
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    glFinishFenceNV
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_glFinishFenceNV
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    glFlushVertexArrayRangeNV
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_glFlushVertexArrayRangeNV
  (JNIEnv *, jclass);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    glFogCoordfEXT
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_glFogCoordfEXT
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    nglFogCoordPointerEXT
 * Signature: (IILjava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_nglFogCoordPointerEXT
  (JNIEnv *, jclass, jint, jint, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    glFreeObjectBufferATI
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_glFreeObjectBufferATI
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    nglGenFencesNV
 * Signature: (ILjava/nio/IntBuffer;I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_nglGenFencesNV
  (JNIEnv *, jclass, jint, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    glGenFragmentShadersATI
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_lwjgl_opengl_GL_glGenFragmentShadersATI
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    nglGenOcclusionQueriesNV
 * Signature: (ILjava/nio/IntBuffer;I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_nglGenOcclusionQueriesNV
  (JNIEnv *, jclass, jint, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    nglGenProgramsARB
 * Signature: (ILjava/nio/IntBuffer;I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_nglGenProgramsARB
  (JNIEnv *, jclass, jint, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    nglGenProgramsNV
 * Signature: (ILjava/nio/IntBuffer;I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_nglGenProgramsNV
  (JNIEnv *, jclass, jint, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    glGenSymbolsEXT
 * Signature: (IIII)I
 */
JNIEXPORT jint JNICALL Java_org_lwjgl_opengl_GL_glGenSymbolsEXT
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    glGenVertexShadersEXT
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_lwjgl_opengl_GL_glGenVertexShadersEXT
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    nglGetArrayObjectfvATI
 * Signature: (IILjava/nio/FloatBuffer;I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_nglGetArrayObjectfvATI
  (JNIEnv *, jclass, jint, jint, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    nglGetArrayObjectivATI
 * Signature: (IILjava/nio/IntBuffer;I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_nglGetArrayObjectivATI
  (JNIEnv *, jclass, jint, jint, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    nglGetCombinerInputParameterfvNV
 * Signature: (IIIILjava/nio/FloatBuffer;I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_nglGetCombinerInputParameterfvNV
  (JNIEnv *, jclass, jint, jint, jint, jint, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    nglGetCombinerInputParameterivNV
 * Signature: (IIIILjava/nio/IntBuffer;I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_nglGetCombinerInputParameterivNV
  (JNIEnv *, jclass, jint, jint, jint, jint, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    nglGetCombinerOutputParameterfvNV
 * Signature: (IIILjava/nio/FloatBuffer;I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_nglGetCombinerOutputParameterfvNV
  (JNIEnv *, jclass, jint, jint, jint, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    nglGetCombinerOutputParameterivNV
 * Signature: (IIILjava/nio/IntBuffer;I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_nglGetCombinerOutputParameterivNV
  (JNIEnv *, jclass, jint, jint, jint, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    nglGetCombinerStageParameterfvNV
 * Signature: (IILjava/nio/FloatBuffer;I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_nglGetCombinerStageParameterfvNV
  (JNIEnv *, jclass, jint, jint, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    nglGetCompressedTexImageARB
 * Signature: (IILjava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_nglGetCompressedTexImageARB
  (JNIEnv *, jclass, jint, jint, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    nglGetFenceivNV
 * Signature: (IILjava/nio/IntBuffer;I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_nglGetFenceivNV
  (JNIEnv *, jclass, jint, jint, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    nglGetFinalCombinerInputParameterfvNV
 * Signature: (IILjava/nio/FloatBuffer;I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_nglGetFinalCombinerInputParameterfvNV
  (JNIEnv *, jclass, jint, jint, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    nglGetFinalCombinerInputParameterivNV
 * Signature: (IILjava/nio/IntBuffer;I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_nglGetFinalCombinerInputParameterivNV
  (JNIEnv *, jclass, jint, jint, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    nglGetInvariantBooleanvEXT
 * Signature: (IILjava/nio/ByteBuffer;I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_nglGetInvariantBooleanvEXT
  (JNIEnv *, jclass, jint, jint, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    nglGetInvariantFloatvEXT
 * Signature: (IILjava/nio/FloatBuffer;I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_nglGetInvariantFloatvEXT
  (JNIEnv *, jclass, jint, jint, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    nglGetInvariantIntegervEXT
 * Signature: (IILjava/nio/IntBuffer;I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_nglGetInvariantIntegervEXT
  (JNIEnv *, jclass, jint, jint, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    nglGetLocalConstantBooleanvEXT
 * Signature: (IILjava/nio/ByteBuffer;I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_nglGetLocalConstantBooleanvEXT
  (JNIEnv *, jclass, jint, jint, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    nglGetLocalConstantFloatvEXT
 * Signature: (IILjava/nio/FloatBuffer;I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_nglGetLocalConstantFloatvEXT
  (JNIEnv *, jclass, jint, jint, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    nglGetLocalConstantIntegervEXT
 * Signature: (IILjava/nio/IntBuffer;I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_nglGetLocalConstantIntegervEXT
  (JNIEnv *, jclass, jint, jint, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    nglGetMapAttribParameterfvNV
 * Signature: (IIILjava/nio/FloatBuffer;I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_nglGetMapAttribParameterfvNV
  (JNIEnv *, jclass, jint, jint, jint, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    nglGetMapAttribParameterivNV
 * Signature: (IIILjava/nio/IntBuffer;I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_nglGetMapAttribParameterivNV
  (JNIEnv *, jclass, jint, jint, jint, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    nglGetMapControlPointsNV
 * Signature: (IIIIIZLjava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_nglGetMapControlPointsNV
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jboolean, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    nglGetMapParameterfvNV
 * Signature: (IILjava/nio/FloatBuffer;I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_nglGetMapParameterfvNV
  (JNIEnv *, jclass, jint, jint, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    nglGetMapParameterivNV
 * Signature: (IILjava/nio/IntBuffer;I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_nglGetMapParameterivNV
  (JNIEnv *, jclass, jint, jint, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    nglGetObjectBufferfvATI
 * Signature: (IILjava/nio/FloatBuffer;I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_nglGetObjectBufferfvATI
  (JNIEnv *, jclass, jint, jint, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    nglGetObjectBufferivATI
 * Signature: (IILjava/nio/IntBuffer;I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_nglGetObjectBufferivATI
  (JNIEnv *, jclass, jint, jint, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    nglGetOcclusionQueryivNV
 * Signature: (IILjava/nio/IntBuffer;I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_nglGetOcclusionQueryivNV
  (JNIEnv *, jclass, jint, jint, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    nglGetOcclusionQueryuivNV
 * Signature: (IILjava/nio/IntBuffer;I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_nglGetOcclusionQueryuivNV
  (JNIEnv *, jclass, jint, jint, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    nglGetProgramEnvParameterfvARB
 * Signature: (IILjava/nio/FloatBuffer;I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_nglGetProgramEnvParameterfvARB
  (JNIEnv *, jclass, jint, jint, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    nglGetProgramivARB
 * Signature: (IILjava/nio/IntBuffer;I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_nglGetProgramivARB
  (JNIEnv *, jclass, jint, jint, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    nglGetProgramivNV
 * Signature: (IILjava/nio/IntBuffer;I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_nglGetProgramivNV
  (JNIEnv *, jclass, jint, jint, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    nglGetProgramLocalParameterfvARB
 * Signature: (IILjava/nio/FloatBuffer;I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_nglGetProgramLocalParameterfvARB
  (JNIEnv *, jclass, jint, jint, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    nglGetProgramParameterfvNV
 * Signature: (IIILjava/nio/FloatBuffer;I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_nglGetProgramParameterfvNV
  (JNIEnv *, jclass, jint, jint, jint, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    nglGetProgramStringARB
 * Signature: (IILjava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_nglGetProgramStringARB
  (JNIEnv *, jclass, jint, jint, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    nglGetProgramStringNV
 * Signature: (IILjava/nio/ByteBuffer;I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_nglGetProgramStringNV
  (JNIEnv *, jclass, jint, jint, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    nglGetTexBumpParameterfvATI
 * Signature: (ILjava/nio/FloatBuffer;I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_nglGetTexBumpParameterfvATI
  (JNIEnv *, jclass, jint, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    nglGetTexBumpParameterivATI
 * Signature: (ILjava/nio/IntBuffer;I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_nglGetTexBumpParameterivATI
  (JNIEnv *, jclass, jint, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    nglGetTrackMatrixivNV
 * Signature: (IIILjava/nio/IntBuffer;I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_nglGetTrackMatrixivNV
  (JNIEnv *, jclass, jint, jint, jint, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    nglGetVariantArrayObjectfvATI
 * Signature: (IILjava/nio/FloatBuffer;I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_nglGetVariantArrayObjectfvATI
  (JNIEnv *, jclass, jint, jint, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    nglGetVariantArrayObjectivATI
 * Signature: (IILjava/nio/IntBuffer;I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_nglGetVariantArrayObjectivATI
  (JNIEnv *, jclass, jint, jint, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    nglGetVariantBooleanvEXT
 * Signature: (IILjava/nio/ByteBuffer;I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_nglGetVariantBooleanvEXT
  (JNIEnv *, jclass, jint, jint, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    nglGetVariantFloatvEXT
 * Signature: (IILjava/nio/FloatBuffer;I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_nglGetVariantFloatvEXT
  (JNIEnv *, jclass, jint, jint, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    nglGetVariantIntegervEXT
 * Signature: (IILjava/nio/IntBuffer;I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_nglGetVariantIntegervEXT
  (JNIEnv *, jclass, jint, jint, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    glGetVariantPointerEXT
 * Signature: (III)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_org_lwjgl_opengl_GL_glGetVariantPointerEXT
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    nglGetVertexAttribfvARB
 * Signature: (IILjava/nio/FloatBuffer;I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_nglGetVertexAttribfvARB
  (JNIEnv *, jclass, jint, jint, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    nglGetVertexAttribfvNV
 * Signature: (IILjava/nio/FloatBuffer;I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_nglGetVertexAttribfvNV
  (JNIEnv *, jclass, jint, jint, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    nglGetVertexAttribivARB
 * Signature: (IILjava/nio/IntBuffer;I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_nglGetVertexAttribivARB
  (JNIEnv *, jclass, jint, jint, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    nglGetVertexAttribivNV
 * Signature: (IILjava/nio/IntBuffer;I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_nglGetVertexAttribivNV
  (JNIEnv *, jclass, jint, jint, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    glGetVertexAttribPointerARB
 * Signature: (III)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_org_lwjgl_opengl_GL_glGetVertexAttribPointerARB
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    glGetVertexAttribPointerNV
 * Signature: (III)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_org_lwjgl_opengl_GL_glGetVertexAttribPointerNV
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    glInsertComponentEXT
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_glInsertComponentEXT
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    glIsFenceNV
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_lwjgl_opengl_GL_glIsFenceNV
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    glIsObjectBufferATI
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_lwjgl_opengl_GL_glIsObjectBufferATI
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    glIsOcclusionQueryNV
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_lwjgl_opengl_GL_glIsOcclusionQueryNV
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    glIsProgramARB
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_lwjgl_opengl_GL_glIsProgramARB
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    glIsProgramNV
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_lwjgl_opengl_GL_glIsProgramNV
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    glIsVariantEnabledEXT
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_org_lwjgl_opengl_GL_glIsVariantEnabledEXT
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    nglLoadProgramNV
 * Signature: (IIILjava/nio/ByteBuffer;I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_nglLoadProgramNV
  (JNIEnv *, jclass, jint, jint, jint, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    nglLoadTransposeMatrixfARB
 * Signature: (Ljava/nio/FloatBuffer;I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_nglLoadTransposeMatrixfARB
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    glLockArraysEXT
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_glLockArraysEXT
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    nglMapControlPointsNV
 * Signature: (IIIIIIIZLjava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_nglMapControlPointsNV
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jint, jboolean, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    nglMapParameterfvNV
 * Signature: (IILjava/nio/FloatBuffer;I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_nglMapParameterfvNV
  (JNIEnv *, jclass, jint, jint, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    nglMapParameterivNV
 * Signature: (IILjava/nio/IntBuffer;I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_nglMapParameterivNV
  (JNIEnv *, jclass, jint, jint, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    nglMatrixIndexPointerARB
 * Signature: (IIILjava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_nglMatrixIndexPointerARB
  (JNIEnv *, jclass, jint, jint, jint, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    nglMatrixIndexubvARB
 * Signature: (ILjava/nio/ByteBuffer;I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_nglMatrixIndexubvARB
  (JNIEnv *, jclass, jint, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    nglMatrixIndexuivARB
 * Signature: (ILjava/nio/IntBuffer;I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_nglMatrixIndexuivARB
  (JNIEnv *, jclass, jint, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    nglMatrixIndexusvARB
 * Signature: (ILjava/nio/ShortBuffer;I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_nglMatrixIndexusvARB
  (JNIEnv *, jclass, jint, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    nglMultiDrawArraysEXT
 * Signature: (ILjava/nio/IntBuffer;ILjava/nio/IntBuffer;II)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_nglMultiDrawArraysEXT
  (JNIEnv *, jclass, jint, jobject, jint, jobject, jint, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    glMultiTexCoord1fARB
 * Signature: (IF)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_glMultiTexCoord1fARB
  (JNIEnv *, jclass, jint, jfloat);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    glMultiTexCoord1iARB
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_glMultiTexCoord1iARB
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    glMultiTexCoord1sARB
 * Signature: (IS)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_glMultiTexCoord1sARB
  (JNIEnv *, jclass, jint, jshort);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    glMultiTexCoord2fARB
 * Signature: (IFF)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_glMultiTexCoord2fARB
  (JNIEnv *, jclass, jint, jfloat, jfloat);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    glMultiTexCoord2iARB
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_glMultiTexCoord2iARB
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    glMultiTexCoord2sARB
 * Signature: (ISS)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_glMultiTexCoord2sARB
  (JNIEnv *, jclass, jint, jshort, jshort);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    glMultiTexCoord3fARB
 * Signature: (IFFF)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_glMultiTexCoord3fARB
  (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    glMultiTexCoord3iARB
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_glMultiTexCoord3iARB
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    glMultiTexCoord3sARB
 * Signature: (ISSS)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_glMultiTexCoord3sARB
  (JNIEnv *, jclass, jint, jshort, jshort, jshort);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    glMultiTexCoord4fARB
 * Signature: (IFFFF)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_glMultiTexCoord4fARB
  (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    glMultiTexCoord4iARB
 * Signature: (IIIII)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_glMultiTexCoord4iARB
  (JNIEnv *, jclass, jint, jint, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    glMultiTexCoord4sARB
 * Signature: (ISSSS)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_glMultiTexCoord4sARB
  (JNIEnv *, jclass, jint, jshort, jshort, jshort, jshort);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    nglMultTransposeMatrixfARB
 * Signature: (Ljava/nio/FloatBuffer;I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_nglMultTransposeMatrixfARB
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    nglNewObjectBufferATI
 * Signature: (ILjava/nio/Buffer;II)I
 */
JNIEXPORT jint JNICALL Java_org_lwjgl_opengl_GL_nglNewObjectBufferATI
  (JNIEnv *, jclass, jint, jobject, jint, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    glNormalStream3bATI
 * Signature: (IBBB)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_glNormalStream3bATI
  (JNIEnv *, jclass, jint, jbyte, jbyte, jbyte);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    glNormalStream3fATI
 * Signature: (IFFF)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_glNormalStream3fATI
  (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    glNormalStream3iATI
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_glNormalStream3iATI
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    glNormalStream3sATI
 * Signature: (ISSS)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_glNormalStream3sATI
  (JNIEnv *, jclass, jint, jshort, jshort, jshort);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    glPassTexCoordATI
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_glPassTexCoordATI
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    glPNTrianglesfATI
 * Signature: (IF)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_glPNTrianglesfATI
  (JNIEnv *, jclass, jint, jfloat);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    glPNTrianglesiATI
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_glPNTrianglesiATI
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    glStencilOpSeparateATI
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_glStencilOpSeparateATI
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    glStencilFuncSeparateATI
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_glStencilFuncSeparateATI
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    glPointParameterfARB
 * Signature: (IF)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_glPointParameterfARB
  (JNIEnv *, jclass, jint, jfloat);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    glPointParameterfEXT
 * Signature: (IF)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_glPointParameterfEXT
  (JNIEnv *, jclass, jint, jfloat);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    nglPointParameterfvARB
 * Signature: (ILjava/nio/FloatBuffer;I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_nglPointParameterfvARB
  (JNIEnv *, jclass, jint, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    nglPointParameterfvEXT
 * Signature: (ILjava/nio/FloatBuffer;I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_nglPointParameterfvEXT
  (JNIEnv *, jclass, jint, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    glPointParameteriNV
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_glPointParameteriNV
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    nglPointParameterivNV
 * Signature: (ILjava/nio/IntBuffer;I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_nglPointParameterivNV
  (JNIEnv *, jclass, jint, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    glProgramEnvParameter4fARB
 * Signature: (IIFFFF)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_glProgramEnvParameter4fARB
  (JNIEnv *, jclass, jint, jint, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    glProgramLocalParameter4fARB
 * Signature: (IIFFFF)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_glProgramLocalParameter4fARB
  (JNIEnv *, jclass, jint, jint, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    glProgramParameter4fNV
 * Signature: (IIFFFF)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_glProgramParameter4fNV
  (JNIEnv *, jclass, jint, jint, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    nglProgramParameters4fvNV
 * Signature: (IIILjava/nio/FloatBuffer;I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_nglProgramParameters4fvNV
  (JNIEnv *, jclass, jint, jint, jint, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    nglProgramStringARB
 * Signature: (IIILjava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_nglProgramStringARB
  (JNIEnv *, jclass, jint, jint, jint, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    nglRequestResidentProgramsNV
 * Signature: (ILjava/nio/IntBuffer;I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_nglRequestResidentProgramsNV
  (JNIEnv *, jclass, jint, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    glSampleCoverageARB
 * Signature: (FZ)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_glSampleCoverageARB
  (JNIEnv *, jclass, jfloat, jboolean);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    glSampleMapATI
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_glSampleMapATI
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    glSecondaryColor3bEXT
 * Signature: (BBB)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_glSecondaryColor3bEXT
  (JNIEnv *, jclass, jbyte, jbyte, jbyte);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    glSecondaryColor3fEXT
 * Signature: (FFF)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_glSecondaryColor3fEXT
  (JNIEnv *, jclass, jfloat, jfloat, jfloat);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    glSecondaryColor3ubEXT
 * Signature: (BBB)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_glSecondaryColor3ubEXT
  (JNIEnv *, jclass, jbyte, jbyte, jbyte);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    nglSecondaryColorPointerEXT
 * Signature: (IIILjava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_nglSecondaryColorPointerEXT
  (JNIEnv *, jclass, jint, jint, jint, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    glSetFenceNV
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_glSetFenceNV
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    nglSetFragmentShaderConstantATI
 * Signature: (ILjava/nio/FloatBuffer;I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_nglSetFragmentShaderConstantATI
  (JNIEnv *, jclass, jint, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    nglSetInvariantEXT
 * Signature: (IILjava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_nglSetInvariantEXT
  (JNIEnv *, jclass, jint, jint, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    nglSetLocalConstantEXT
 * Signature: (IILjava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_nglSetLocalConstantEXT
  (JNIEnv *, jclass, jint, jint, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    glShaderOp1EXT
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_glShaderOp1EXT
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    glShaderOp2EXT
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_glShaderOp2EXT
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    glShaderOp3EXT
 * Signature: (IIIII)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_glShaderOp3EXT
  (JNIEnv *, jclass, jint, jint, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    glSwizzleEXT
 * Signature: (IIIIII)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_glSwizzleEXT
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    glTestFenceNV
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_lwjgl_opengl_GL_glTestFenceNV
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    nglTexBumpParameterfvATI
 * Signature: (ILjava/nio/FloatBuffer;I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_nglTexBumpParameterfvATI
  (JNIEnv *, jclass, jint, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    nglTexBumpParameterivATI
 * Signature: (ILjava/nio/IntBuffer;I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_nglTexBumpParameterivATI
  (JNIEnv *, jclass, jint, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    glTrackMatrixNV
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_glTrackMatrixNV
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    glUnlockArraysEXT
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_glUnlockArraysEXT
  (JNIEnv *, jclass);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    nglUpdateObjectBufferATI
 * Signature: (IIILjava/nio/Buffer;II)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_nglUpdateObjectBufferATI
  (JNIEnv *, jclass, jint, jint, jint, jobject, jint, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    glVariantArrayObjectATI
 * Signature: (IIIII)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_glVariantArrayObjectATI
  (JNIEnv *, jclass, jint, jint, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    nglVariantbvEXT
 * Signature: (ILjava/nio/ByteBuffer;I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_nglVariantbvEXT
  (JNIEnv *, jclass, jint, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    nglVariantfvEXT
 * Signature: (ILjava/nio/FloatBuffer;I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_nglVariantfvEXT
  (JNIEnv *, jclass, jint, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    nglVariantivEXT
 * Signature: (ILjava/nio/IntBuffer;I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_nglVariantivEXT
  (JNIEnv *, jclass, jint, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    nglVariantPointerEXT
 * Signature: (IIILjava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_nglVariantPointerEXT
  (JNIEnv *, jclass, jint, jint, jint, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    nglVariantsvEXT
 * Signature: (ILjava/nio/ShortBuffer;I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_nglVariantsvEXT
  (JNIEnv *, jclass, jint, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    nglVariantubvEXT
 * Signature: (ILjava/nio/ByteBuffer;I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_nglVariantubvEXT
  (JNIEnv *, jclass, jint, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    nglVariantuivEXT
 * Signature: (ILjava/nio/IntBuffer;I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_nglVariantuivEXT
  (JNIEnv *, jclass, jint, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    nglVariantusvEXT
 * Signature: (ILjava/nio/ShortBuffer;I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_nglVariantusvEXT
  (JNIEnv *, jclass, jint, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    nglVertexArrayRangeNV
 * Signature: (ILjava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_nglVertexArrayRangeNV
  (JNIEnv *, jclass, jint, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    glVertexAttrib1fARB
 * Signature: (IF)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_glVertexAttrib1fARB
  (JNIEnv *, jclass, jint, jfloat);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    glVertexAttrib1fNV
 * Signature: (IF)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_glVertexAttrib1fNV
  (JNIEnv *, jclass, jint, jfloat);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    glVertexAttrib1sARB
 * Signature: (IS)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_glVertexAttrib1sARB
  (JNIEnv *, jclass, jint, jshort);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    glVertexAttrib1sNV
 * Signature: (IS)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_glVertexAttrib1sNV
  (JNIEnv *, jclass, jint, jshort);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    glVertexAttrib2fARB
 * Signature: (IFF)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_glVertexAttrib2fARB
  (JNIEnv *, jclass, jint, jfloat, jfloat);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    glVertexAttrib2fNV
 * Signature: (IFF)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_glVertexAttrib2fNV
  (JNIEnv *, jclass, jint, jfloat, jfloat);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    glVertexAttrib2sARB
 * Signature: (ISS)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_glVertexAttrib2sARB
  (JNIEnv *, jclass, jint, jshort, jshort);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    glVertexAttrib2sNV
 * Signature: (ISS)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_glVertexAttrib2sNV
  (JNIEnv *, jclass, jint, jshort, jshort);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    glVertexAttrib3fARB
 * Signature: (IFFF)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_glVertexAttrib3fARB
  (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    glVertexAttrib3fNV
 * Signature: (IFFF)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_glVertexAttrib3fNV
  (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    glVertexAttrib3sARB
 * Signature: (ISSS)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_glVertexAttrib3sARB
  (JNIEnv *, jclass, jint, jshort, jshort, jshort);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    glVertexAttrib3sNV
 * Signature: (ISSS)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_glVertexAttrib3sNV
  (JNIEnv *, jclass, jint, jshort, jshort, jshort);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    nglVertexAttrib4bvARB
 * Signature: (ILjava/nio/ByteBuffer;I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_nglVertexAttrib4bvARB
  (JNIEnv *, jclass, jint, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    glVertexAttrib4fARB
 * Signature: (IFFFF)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_glVertexAttrib4fARB
  (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    glVertexAttrib4fNV
 * Signature: (IFFFF)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_glVertexAttrib4fNV
  (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    nglVertexAttrib4ivARB
 * Signature: (ILjava/nio/IntBuffer;I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_nglVertexAttrib4ivARB
  (JNIEnv *, jclass, jint, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    nglVertexAttrib4NbvARB
 * Signature: (ILjava/nio/ByteBuffer;I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_nglVertexAttrib4NbvARB
  (JNIEnv *, jclass, jint, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    nglVertexAttrib4NivARB
 * Signature: (ILjava/nio/IntBuffer;I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_nglVertexAttrib4NivARB
  (JNIEnv *, jclass, jint, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    nglVertexAttrib4NsvARB
 * Signature: (ILjava/nio/ShortBuffer;I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_nglVertexAttrib4NsvARB
  (JNIEnv *, jclass, jint, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    glVertexAttrib4NubARB
 * Signature: (IBBBB)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_glVertexAttrib4NubARB
  (JNIEnv *, jclass, jint, jbyte, jbyte, jbyte, jbyte);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    nglVertexAttrib4NubvARB
 * Signature: (ILjava/nio/ByteBuffer;I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_nglVertexAttrib4NubvARB
  (JNIEnv *, jclass, jint, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    nglVertexAttrib4NuivARB
 * Signature: (ILjava/nio/IntBuffer;I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_nglVertexAttrib4NuivARB
  (JNIEnv *, jclass, jint, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    nglVertexAttrib4NusvARB
 * Signature: (ILjava/nio/ShortBuffer;I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_nglVertexAttrib4NusvARB
  (JNIEnv *, jclass, jint, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    glVertexAttrib4sARB
 * Signature: (ISSSS)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_glVertexAttrib4sARB
  (JNIEnv *, jclass, jint, jshort, jshort, jshort, jshort);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    glVertexAttrib4sNV
 * Signature: (ISSSS)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_glVertexAttrib4sNV
  (JNIEnv *, jclass, jint, jshort, jshort, jshort, jshort);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    glVertexAttrib4ubNV
 * Signature: (IBBBB)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_glVertexAttrib4ubNV
  (JNIEnv *, jclass, jint, jbyte, jbyte, jbyte, jbyte);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    nglVertexAttrib4ubvARB
 * Signature: (ILjava/nio/ByteBuffer;I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_nglVertexAttrib4ubvARB
  (JNIEnv *, jclass, jint, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    nglVertexAttrib4ubvNV
 * Signature: (ILjava/nio/ByteBuffer;I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_nglVertexAttrib4ubvNV
  (JNIEnv *, jclass, jint, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    nglVertexAttrib4uivARB
 * Signature: (ILjava/nio/IntBuffer;I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_nglVertexAttrib4uivARB
  (JNIEnv *, jclass, jint, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    nglVertexAttrib4usvARB
 * Signature: (ILjava/nio/ShortBuffer;I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_nglVertexAttrib4usvARB
  (JNIEnv *, jclass, jint, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    nglVertexAttribPointerARB
 * Signature: (IIIZILjava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_nglVertexAttribPointerARB
  (JNIEnv *, jclass, jint, jint, jint, jboolean, jint, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    nglVertexAttribPointerARBVBO
 * Signature: (IIIZII)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_nglVertexAttribPointerARBVBO
  (JNIEnv *, jclass, jint, jint, jint, jboolean, jint, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    nglVertexAttribPointerNV
 * Signature: (IIIILjava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_nglVertexAttribPointerNV
  (JNIEnv *, jclass, jint, jint, jint, jint, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    nglVertexAttribs1fvNV
 * Signature: (IILjava/nio/FloatBuffer;I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_nglVertexAttribs1fvNV
  (JNIEnv *, jclass, jint, jint, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    nglVertexAttribs1svNV
 * Signature: (IILjava/nio/ShortBuffer;I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_nglVertexAttribs1svNV
  (JNIEnv *, jclass, jint, jint, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    nglVertexAttribs2fvNV
 * Signature: (IILjava/nio/FloatBuffer;I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_nglVertexAttribs2fvNV
  (JNIEnv *, jclass, jint, jint, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    nglVertexAttribs2svNV
 * Signature: (IILjava/nio/ShortBuffer;I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_nglVertexAttribs2svNV
  (JNIEnv *, jclass, jint, jint, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    nglVertexAttribs3fvNV
 * Signature: (IILjava/nio/FloatBuffer;I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_nglVertexAttribs3fvNV
  (JNIEnv *, jclass, jint, jint, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    nglVertexAttribs3svNV
 * Signature: (IILjava/nio/ShortBuffer;I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_nglVertexAttribs3svNV
  (JNIEnv *, jclass, jint, jint, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    nglVertexAttribs4fvNV
 * Signature: (IILjava/nio/FloatBuffer;I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_nglVertexAttribs4fvNV
  (JNIEnv *, jclass, jint, jint, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    nglVertexAttribs4svNV
 * Signature: (IILjava/nio/ShortBuffer;I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_nglVertexAttribs4svNV
  (JNIEnv *, jclass, jint, jint, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    nglVertexAttribs4ubvNV
 * Signature: (IILjava/nio/ByteBuffer;I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_nglVertexAttribs4ubvNV
  (JNIEnv *, jclass, jint, jint, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    glVertexBlendARB
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_glVertexBlendARB
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    glVertexBlendEnvfATI
 * Signature: (IF)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_glVertexBlendEnvfATI
  (JNIEnv *, jclass, jint, jfloat);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    glVertexBlendEnviATI
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_glVertexBlendEnviATI
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    glVertexStream2fATI
 * Signature: (IFF)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_glVertexStream2fATI
  (JNIEnv *, jclass, jint, jfloat, jfloat);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    glVertexStream2iATI
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_glVertexStream2iATI
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    glVertexStream2sATI
 * Signature: (ISS)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_glVertexStream2sATI
  (JNIEnv *, jclass, jint, jshort, jshort);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    glVertexStream3fATI
 * Signature: (IFFF)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_glVertexStream3fATI
  (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    glVertexStream3iATI
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_glVertexStream3iATI
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    glVertexStream3sATI
 * Signature: (ISSS)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_glVertexStream3sATI
  (JNIEnv *, jclass, jint, jshort, jshort, jshort);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    glVertexStream4fATI
 * Signature: (IFFFF)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_glVertexStream4fATI
  (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    glVertexStream4iATI
 * Signature: (IIIII)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_glVertexStream4iATI
  (JNIEnv *, jclass, jint, jint, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    glVertexStream4sATI
 * Signature: (ISSSS)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_glVertexStream4sATI
  (JNIEnv *, jclass, jint, jshort, jshort, jshort, jshort);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    glVertexWeightfEXT
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_glVertexWeightfEXT
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    nglVertexWeightPointerEXT
 * Signature: (IIILjava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_nglVertexWeightPointerEXT
  (JNIEnv *, jclass, jint, jint, jint, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    nglWeightbvARB
 * Signature: (ILjava/nio/ByteBuffer;I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_nglWeightbvARB
  (JNIEnv *, jclass, jint, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    nglWeightfvARB
 * Signature: (ILjava/nio/FloatBuffer;I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_nglWeightfvARB
  (JNIEnv *, jclass, jint, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    nglWeightivARB
 * Signature: (ILjava/nio/IntBuffer;I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_nglWeightivARB
  (JNIEnv *, jclass, jint, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    nglWeightPointerARB
 * Signature: (IIILjava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_nglWeightPointerARB
  (JNIEnv *, jclass, jint, jint, jint, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    nglWeightPointerARBVBO
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_nglWeightPointerARBVBO
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    nglWeightsvARB
 * Signature: (ILjava/nio/ShortBuffer;I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_nglWeightsvARB
  (JNIEnv *, jclass, jint, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    nglWeightubvARB
 * Signature: (ILjava/nio/ByteBuffer;I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_nglWeightubvARB
  (JNIEnv *, jclass, jint, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    nglWeightuivARB
 * Signature: (ILjava/nio/IntBuffer;I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_nglWeightuivARB
  (JNIEnv *, jclass, jint, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    nglWeightusvARB
 * Signature: (ILjava/nio/ShortBuffer;I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_nglWeightusvARB
  (JNIEnv *, jclass, jint, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    glXAllocateMemoryNV
 * Signature: (IFFF)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_org_lwjgl_opengl_GL_glXAllocateMemoryNV
  (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    glXFreeMemoryNV
 * Signature: (Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_glXFreeMemoryNV
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    wglAllocateMemoryNV
 * Signature: (IFFF)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_org_lwjgl_opengl_GL_wglAllocateMemoryNV
  (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    wglBindTexImageARB
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_org_lwjgl_opengl_GL_wglBindTexImageARB
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    wglFreeMemoryNV
 * Signature: (Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_wglFreeMemoryNV
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    wglGetCurrentReadDCARB
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_lwjgl_opengl_GL_wglGetCurrentReadDCARB
  (JNIEnv *, jclass);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    wglGetExtensionsStringARB
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_lwjgl_opengl_GL_wglGetExtensionsStringARB
  (JNIEnv *, jclass);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    wglGetExtensionsStringEXT
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_lwjgl_opengl_GL_wglGetExtensionsStringEXT
  (JNIEnv *, jclass);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    wglGetSwapIntervalEXT
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_lwjgl_opengl_GL_wglGetSwapIntervalEXT
  (JNIEnv *, jclass);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    wglReleaseTexImageARB
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_org_lwjgl_opengl_GL_wglReleaseTexImageARB
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    wglSwapIntervalEXT
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_lwjgl_opengl_GL_wglSwapIntervalEXT
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    glWindowPos2fARB
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_glWindowPos2fARB
  (JNIEnv *, jclass, jfloat, jfloat);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    glWindowPos2iARB
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_glWindowPos2iARB
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    glWindowPos2sARB
 * Signature: (SS)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_glWindowPos2sARB
  (JNIEnv *, jclass, jshort, jshort);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    glWindowPos3fARB
 * Signature: (FFF)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_glWindowPos3fARB
  (JNIEnv *, jclass, jfloat, jfloat, jfloat);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    glWindowPos3iARB
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_glWindowPos3iARB
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    glWindowPos3sARB
 * Signature: (SSS)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_glWindowPos3sARB
  (JNIEnv *, jclass, jshort, jshort, jshort);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    glWriteMaskEXT
 * Signature: (IIIIII)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_glWriteMaskEXT
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    nglBindBufferARB
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_nglBindBufferARB
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    nglDeleteBuffersARB
 * Signature: (ILjava/nio/IntBuffer;I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_nglDeleteBuffersARB
  (JNIEnv *, jclass, jint, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    nglGenBuffersARB
 * Signature: (ILjava/nio/IntBuffer;I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_nglGenBuffersARB
  (JNIEnv *, jclass, jint, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    glIsBufferARB
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_lwjgl_opengl_GL_glIsBufferARB
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    nglBufferDataARB
 * Signature: (IILjava/nio/Buffer;II)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_nglBufferDataARB
  (JNIEnv *, jclass, jint, jint, jobject, jint, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    nglBufferSubDataARB
 * Signature: (IIILjava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_nglBufferSubDataARB
  (JNIEnv *, jclass, jint, jint, jint, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    nglGetBufferSubDataARB
 * Signature: (IIILjava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_nglGetBufferSubDataARB
  (JNIEnv *, jclass, jint, jint, jint, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    glMapBufferARB
 * Signature: (IIILjava/nio/ByteBuffer;)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_org_lwjgl_opengl_GL_glMapBufferARB
  (JNIEnv *, jclass, jint, jint, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    glUnmapBufferARB
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_lwjgl_opengl_GL_glUnmapBufferARB
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    nglGetBufferParameterivARB
 * Signature: (IILjava/nio/IntBuffer;I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GL_nglGetBufferParameterivARB
  (JNIEnv *, jclass, jint, jint, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_GL
 * Method:    glGetBufferPointerARB
 * Signature: (III)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_org_lwjgl_opengl_GL_glGetBufferPointerARB
  (JNIEnv *, jclass, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
