/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_lwjgl_openal_ALUT */

#ifndef _Included_org_lwjgl_openal_ALUT
#define _Included_org_lwjgl_openal_ALUT
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_lwjgl_openal_ALUT
 * Method:    init
 * Signature: ([Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_openal_ALUT_init
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     org_lwjgl_openal_ALUT
 * Method:    loadWAVFile
 * Signature: (Ljava/lang/String;)Lorg/lwjgl/openal/ALUTLoadWAVFile;
 */
JNIEXPORT jobject JNICALL Java_org_lwjgl_openal_ALUT_loadWAVFile
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_lwjgl_openal_ALUT
 * Method:    unloadWAV
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_openal_ALUT_unloadWAV
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     org_lwjgl_openal_ALUT
 * Method:    exit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_openal_ALUT_exit
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
