/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_lwjgl_opengl_CoreGL12 */

#ifndef _Included_org_lwjgl_opengl_CoreGL12
#define _Included_org_lwjgl_opengl_CoreGL12
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_lwjgl_opengl_CoreGL12
 * Method:    glColorTable
 * Signature: (IIIIILjava/nio/Buffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL12_glColorTable
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL12
 * Method:    glColorSubTable
 * Signature: (IIIIILjava/nio/Buffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL12_glColorSubTable
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL12
 * Method:    glColorTableParameteriv
 * Signature: (IILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL12_glColorTableParameteriv
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL12
 * Method:    glColorTableParameterfv
 * Signature: (IILjava/nio/FloatBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL12_glColorTableParameterfv
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL12
 * Method:    glCopyColorSubTable
 * Signature: (IIIII)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL12_glCopyColorSubTable
  (JNIEnv *, jclass, jint, jint, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL12
 * Method:    glCopyColorTable
 * Signature: (IIIII)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL12_glCopyColorTable
  (JNIEnv *, jclass, jint, jint, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL12
 * Method:    glGetColorTable
 * Signature: (IIILjava/nio/Buffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL12_glGetColorTable
  (JNIEnv *, jclass, jint, jint, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL12
 * Method:    glGetColorTableParameteriv
 * Signature: (IILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL12_glGetColorTableParameteriv
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL12
 * Method:    glGetColorTableParameterfv
 * Signature: (IILjava/nio/FloatBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL12_glGetColorTableParameterfv
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL12
 * Method:    glBlendEquation
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL12_glBlendEquation
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL12
 * Method:    glBlendColor
 * Signature: (FFFF)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL12_glBlendColor
  (JNIEnv *, jclass, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     org_lwjgl_opengl_CoreGL12
 * Method:    glHistogram
 * Signature: (IIIZ)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL12_glHistogram
  (JNIEnv *, jclass, jint, jint, jint, jboolean);

/*
 * Class:     org_lwjgl_opengl_CoreGL12
 * Method:    glResetHistogram
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL12_glResetHistogram
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL12
 * Method:    glGetHistogram
 * Signature: (IZIILjava/nio/Buffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL12_glGetHistogram
  (JNIEnv *, jclass, jint, jboolean, jint, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL12
 * Method:    glGetHistogramParameterfv
 * Signature: (IILjava/nio/FloatBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL12_glGetHistogramParameterfv
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL12
 * Method:    glGetHistogramParameteriv
 * Signature: (IILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL12_glGetHistogramParameteriv
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL12
 * Method:    glMinmax
 * Signature: (IIZ)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL12_glMinmax
  (JNIEnv *, jclass, jint, jint, jboolean);

/*
 * Class:     org_lwjgl_opengl_CoreGL12
 * Method:    glResetMinmax
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL12_glResetMinmax
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL12
 * Method:    glGetMinmax
 * Signature: (IZIILjava/nio/Buffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL12_glGetMinmax
  (JNIEnv *, jclass, jint, jboolean, jint, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL12
 * Method:    glGetMinmaxParameterfv
 * Signature: (IILjava/nio/FloatBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL12_glGetMinmaxParameterfv
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL12
 * Method:    glGetMinmaxParameteriv
 * Signature: (IILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL12_glGetMinmaxParameteriv
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL12
 * Method:    glConvolutionFilter1D
 * Signature: (IIIIILjava/nio/Buffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL12_glConvolutionFilter1D
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL12
 * Method:    glConvolutionFilter2D
 * Signature: (IIIIIILjava/nio/Buffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL12_glConvolutionFilter2D
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL12
 * Method:    glConvolutionParameterf
 * Signature: (IIF)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL12_glConvolutionParameterf
  (JNIEnv *, jclass, jint, jint, jfloat);

/*
 * Class:     org_lwjgl_opengl_CoreGL12
 * Method:    glConvolutionParameterfv
 * Signature: (IILjava/nio/FloatBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL12_glConvolutionParameterfv
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL12
 * Method:    glConvolutionParameteri
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL12_glConvolutionParameteri
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL12
 * Method:    glConvolutionParameteriv
 * Signature: (IILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL12_glConvolutionParameteriv
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL12
 * Method:    glCopyConvolutionFilter1D
 * Signature: (IIIII)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL12_glCopyConvolutionFilter1D
  (JNIEnv *, jclass, jint, jint, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL12
 * Method:    glCopyConvolutionFilter2D
 * Signature: (IIIIII)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL12_glCopyConvolutionFilter2D
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL12
 * Method:    glGetConvolutionFilter
 * Signature: (IIILjava/nio/Buffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL12_glGetConvolutionFilter
  (JNIEnv *, jclass, jint, jint, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL12
 * Method:    glGetConvolutionParameterfv
 * Signature: (IILjava/nio/FloatBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL12_glGetConvolutionParameterfv
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL12
 * Method:    glGetConvolutionParameteriv
 * Signature: (IILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL12_glGetConvolutionParameteriv
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL12
 * Method:    glSeparableFilter2D
 * Signature: (IIIIIILjava/nio/Buffer;Ljava/nio/Buffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL12_glSeparableFilter2D
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jobject, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL12
 * Method:    glGetSeparableFilter
 * Signature: (IIILjava/nio/Buffer;Ljava/nio/Buffer;Ljava/nio/Buffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL12_glGetSeparableFilter
  (JNIEnv *, jclass, jint, jint, jint, jobject, jobject, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL12
 * Method:    glDrawRangeElements
 * Signature: (IIIIILjava/nio/Buffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL12_glDrawRangeElements
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL12
 * Method:    glTexImage3D
 * Signature: (IIIIIIIIILjava/nio/Buffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL12_glTexImage3D
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jint, jint, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL12
 * Method:    glTexSubImage3D
 * Signature: (IIIIIIIIIILjava/nio/Buffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL12_glTexSubImage3D
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL12
 * Method:    glCopyTexSubImage3D
 * Signature: (IIIIIIIII)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL12_glCopyTexSubImage3D
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
