/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_lwjgl_openal_eax_CoreEAX */

#ifndef _Included_org_lwjgl_openal_eax_CoreEAX
#define _Included_org_lwjgl_openal_eax_CoreEAX
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: created */
#undef org_lwjgl_openal_eax_CoreEAX_BUFFER_GUID
#define org_lwjgl_openal_eax_CoreEAX_BUFFER_GUID 1L
#undef org_lwjgl_openal_eax_CoreEAX_LISTENER_GUID
#define org_lwjgl_openal_eax_CoreEAX_LISTENER_GUID 2L
/*
 * Class:     org_lwjgl_openal_eax_CoreEAX
 * Method:    determineAvailableExtensions
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_openal_eax_CoreEAX_determineAvailableExtensions
  (JNIEnv *, jclass);

/*
 * Class:     org_lwjgl_openal_eax_CoreEAX
 * Method:    neaxGet
 * Signature: (IIILjava/nio/Buffer;II)I
 */
JNIEXPORT jint JNICALL Java_org_lwjgl_openal_eax_CoreEAX_neaxGet
  (JNIEnv *, jclass, jint, jint, jint, jobject, jint, jint);

/*
 * Class:     org_lwjgl_openal_eax_CoreEAX
 * Method:    neaxSet
 * Signature: (IIILjava/nio/Buffer;II)I
 */
JNIEXPORT jint JNICALL Java_org_lwjgl_openal_eax_CoreEAX_neaxSet
  (JNIEnv *, jclass, jint, jint, jint, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
