/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_lwjgl_opengl_CoreGL14 */

#ifndef _Included_org_lwjgl_opengl_CoreGL14
#define _Included_org_lwjgl_opengl_CoreGL14
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_lwjgl_opengl_CoreGL14
 * Method:    glFogCoordf
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL14_glFogCoordf
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     org_lwjgl_opengl_CoreGL14
 * Method:    nglFogCoordPointer
 * Signature: (IILjava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL14_nglFogCoordPointer
  (JNIEnv *, jclass, jint, jint, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL14
 * Method:    nglMultiDrawArrays
 * Signature: (ILjava/nio/IntBuffer;ILjava/nio/IntBuffer;II)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL14_nglMultiDrawArrays
  (JNIEnv *, jclass, jint, jobject, jint, jobject, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL14
 * Method:    glPointParameterf
 * Signature: (IF)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL14_glPointParameterf
  (JNIEnv *, jclass, jint, jfloat);

/*
 * Class:     org_lwjgl_opengl_CoreGL14
 * Method:    nglPointParameter
 * Signature: (ILjava/nio/FloatBuffer;I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL14_nglPointParameter
  (JNIEnv *, jclass, jint, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL14
 * Method:    glSecondaryColor3b
 * Signature: (BBB)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL14_glSecondaryColor3b
  (JNIEnv *, jclass, jbyte, jbyte, jbyte);

/*
 * Class:     org_lwjgl_opengl_CoreGL14
 * Method:    glSecondaryColor3f
 * Signature: (FFF)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL14_glSecondaryColor3f
  (JNIEnv *, jclass, jfloat, jfloat, jfloat);

/*
 * Class:     org_lwjgl_opengl_CoreGL14
 * Method:    glSecondaryColor3ub
 * Signature: (BBB)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL14_glSecondaryColor3ub
  (JNIEnv *, jclass, jbyte, jbyte, jbyte);

/*
 * Class:     org_lwjgl_opengl_CoreGL14
 * Method:    nglSecondaryColorPointer
 * Signature: (IIILjava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL14_nglSecondaryColorPointer
  (JNIEnv *, jclass, jint, jint, jint, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL14
 * Method:    glBlendFuncSeparate
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL14_glBlendFuncSeparate
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL14
 * Method:    glWindowPos2f
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL14_glWindowPos2f
  (JNIEnv *, jclass, jfloat, jfloat);

/*
 * Class:     org_lwjgl_opengl_CoreGL14
 * Method:    glWindowPos2i
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL14_glWindowPos2i
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL14
 * Method:    glWindowPos3f
 * Signature: (FFF)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL14_glWindowPos3f
  (JNIEnv *, jclass, jfloat, jfloat, jfloat);

/*
 * Class:     org_lwjgl_opengl_CoreGL14
 * Method:    glWindowPos3i
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL14_glWindowPos3i
  (JNIEnv *, jclass, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
