/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_lwjgl_input_Joystick */

#ifndef _Included_org_lwjgl_input_Joystick
#define _Included_org_lwjgl_input_Joystick
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: _00024assertionsDisabled */
/* Inaccessible static: created */
/* Inaccessible static: button */
/* Inaccessible static: x */
/* Inaccessible static: y */
/* Inaccessible static: z */
/* Inaccessible static: readBuffer */
/* Inaccessible static: readBufferAddress */
#undef org_lwjgl_input_Joystick_JOYSTICK_EVENT_SIZE
#define org_lwjgl_input_Joystick_JOYSTICK_EVENT_SIZE 20L
#undef org_lwjgl_input_Joystick_JOYSTICK_EVENT_STRIDE
#define org_lwjgl_input_Joystick_JOYSTICK_EVENT_STRIDE 32L
/* Inaccessible static: class_000240 */
/*
 * Class:     org_lwjgl_input_Joystick
 * Method:    initIDs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_input_Joystick_initIDs
  (JNIEnv *, jclass);

/*
 * Class:     org_lwjgl_input_Joystick
 * Method:    nCreate
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_lwjgl_input_Joystick_nCreate
  (JNIEnv *, jclass);

/*
 * Class:     org_lwjgl_input_Joystick
 * Method:    nDestroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_input_Joystick_nDestroy
  (JNIEnv *, jclass);

/*
 * Class:     org_lwjgl_input_Joystick
 * Method:    nPoll
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_input_Joystick_nPoll
  (JNIEnv *, jclass);

/*
 * Class:     org_lwjgl_input_Joystick
 * Method:    nGetNumButtons
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_lwjgl_input_Joystick_nGetNumButtons
  (JNIEnv *, jclass);

/*
 * Class:     org_lwjgl_input_Joystick
 * Method:    nHasZValue
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_lwjgl_input_Joystick_nHasZValue
  (JNIEnv *, jclass);

/*
 * Class:     org_lwjgl_input_Joystick
 * Method:    nRead
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_lwjgl_input_Joystick_nRead
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_lwjgl_input_Joystick
 * Method:    nEnableBuffer
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_lwjgl_input_Joystick_nEnableBuffer
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
