/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_lwjgl_opengl_CoreGL14 */

#ifndef _Included_org_lwjgl_opengl_CoreGL14
#define _Included_org_lwjgl_opengl_CoreGL14
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_lwjgl_opengl_CoreGL14
 * Method:    glFogCoordf
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL14_glFogCoordf
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     org_lwjgl_opengl_CoreGL14
 * Method:    glFogCoordd
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL14_glFogCoordd
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     org_lwjgl_opengl_CoreGL14
 * Method:    glFogCoordPointer
 * Signature: (IILjava/nio/Buffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL14_glFogCoordPointer
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL14
 * Method:    glMultiDrawArrays
 * Signature: (ILjava/nio/IntBuffer;Ljava/nio/IntBuffer;I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL14_glMultiDrawArrays
  (JNIEnv *, jclass, jint, jobject, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL14
 * Method:    glPointParameterf
 * Signature: (IF)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL14_glPointParameterf
  (JNIEnv *, jclass, jint, jfloat);

/*
 * Class:     org_lwjgl_opengl_CoreGL14
 * Method:    glPointParameterfv
 * Signature: (ILjava/nio/FloatBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL14_glPointParameterfv
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL14
 * Method:    glSecondaryColor3b
 * Signature: (BBB)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL14_glSecondaryColor3b
  (JNIEnv *, jclass, jbyte, jbyte, jbyte);

/*
 * Class:     org_lwjgl_opengl_CoreGL14
 * Method:    glSecondaryColor3d
 * Signature: (DDD)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL14_glSecondaryColor3d
  (JNIEnv *, jclass, jdouble, jdouble, jdouble);

/*
 * Class:     org_lwjgl_opengl_CoreGL14
 * Method:    glSecondaryColor3f
 * Signature: (FFF)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL14_glSecondaryColor3f
  (JNIEnv *, jclass, jfloat, jfloat, jfloat);

/*
 * Class:     org_lwjgl_opengl_CoreGL14
 * Method:    glSecondaryColor3i
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL14_glSecondaryColor3i
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL14
 * Method:    glSecondaryColor3s
 * Signature: (SSS)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL14_glSecondaryColor3s
  (JNIEnv *, jclass, jshort, jshort, jshort);

/*
 * Class:     org_lwjgl_opengl_CoreGL14
 * Method:    glSecondaryColor3ub
 * Signature: (BBB)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL14_glSecondaryColor3ub
  (JNIEnv *, jclass, jbyte, jbyte, jbyte);

/*
 * Class:     org_lwjgl_opengl_CoreGL14
 * Method:    glSecondaryColor3ui
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL14_glSecondaryColor3ui
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL14
 * Method:    glSecondaryColor3us
 * Signature: (SSS)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL14_glSecondaryColor3us
  (JNIEnv *, jclass, jshort, jshort, jshort);

/*
 * Class:     org_lwjgl_opengl_CoreGL14
 * Method:    glSecondaryColorPointer
 * Signature: (IIILjava/nio/Buffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL14_glSecondaryColorPointer
  (JNIEnv *, jclass, jint, jint, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL14
 * Method:    glBlendFuncSeparate
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL14_glBlendFuncSeparate
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL14
 * Method:    glWindowPos2d
 * Signature: (DD)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL14_glWindowPos2d
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     org_lwjgl_opengl_CoreGL14
 * Method:    glWindowPos2f
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL14_glWindowPos2f
  (JNIEnv *, jclass, jfloat, jfloat);

/*
 * Class:     org_lwjgl_opengl_CoreGL14
 * Method:    glWindowPos2i
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL14_glWindowPos2i
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL14
 * Method:    glWindowPos2s
 * Signature: (SS)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL14_glWindowPos2s
  (JNIEnv *, jclass, jshort, jshort);

/*
 * Class:     org_lwjgl_opengl_CoreGL14
 * Method:    glWindowPos3d
 * Signature: (DDD)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL14_glWindowPos3d
  (JNIEnv *, jclass, jdouble, jdouble, jdouble);

/*
 * Class:     org_lwjgl_opengl_CoreGL14
 * Method:    glWindowPos3f
 * Signature: (FFF)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL14_glWindowPos3f
  (JNIEnv *, jclass, jfloat, jfloat, jfloat);

/*
 * Class:     org_lwjgl_opengl_CoreGL14
 * Method:    glWindowPos3i
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL14_glWindowPos3i
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL14
 * Method:    glWindowPos3s
 * Signature: (SSS)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL14_glWindowPos3s
  (JNIEnv *, jclass, jshort, jshort, jshort);

#ifdef __cplusplus
}
#endif
#endif
