/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_lwjgl_opengl_CoreGL */

#ifndef _Included_org_lwjgl_opengl_CoreGL
#define _Included_org_lwjgl_opengl_CoreGL
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glAccum
 * Signature: (IF)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glAccum
  (JNIEnv *, jclass, jint, jfloat);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glAlphaFunc
 * Signature: (IF)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glAlphaFunc
  (JNIEnv *, jclass, jint, jfloat);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glColorTable
 * Signature: (IIIIILjava/nio/Buffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glColorTable
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glColorSubTable
 * Signature: (IIIIILjava/nio/Buffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glColorSubTable
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glGetColorTable
 * Signature: (IIILjava/nio/Buffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glGetColorTable
  (JNIEnv *, jclass, jint, jint, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glGetColorTableParameteriv
 * Signature: (IILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glGetColorTableParameteriv
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glGetColorTableParameterfv
 * Signature: (IILjava/nio/FloatBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glGetColorTableParameterfv
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glClearColor
 * Signature: (FFFF)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glClearColor
  (JNIEnv *, jclass, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glClearAccum
 * Signature: (FFFF)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glClearAccum
  (JNIEnv *, jclass, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glClear
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glClear
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glCallLists
 * Signature: (IILjava/nio/Buffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glCallLists
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glCallList
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glCallList
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glBlendFunc
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glBlendFunc
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glBlendColor
 * Signature: (FFFF)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glBlendColor
  (JNIEnv *, jclass, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glBitmap
 * Signature: (IIFFFFLjava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glBitmap
  (JNIEnv *, jclass, jint, jint, jfloat, jfloat, jfloat, jfloat, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glBindTexture
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glBindTexture
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glBegin
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glBegin
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glEnd
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glEnd
  (JNIEnv *, jclass);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glArrayElement
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glArrayElement
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glAreTexturesResident
 * Signature: (ILjava/nio/IntBuffer;Ljava/nio/ByteBuffer;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_lwjgl_opengl_CoreGL_glAreTexturesResident
  (JNIEnv *, jclass, jint, jobject, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glClearDepth
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glClearDepth
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glDeleteLists
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glDeleteLists
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glDeleteTextures
 * Signature: (ILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glDeleteTextures
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glCullFace
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glCullFace
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glCopyTexSubImage2D
 * Signature: (IIIIIIII)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glCopyTexSubImage2D
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glCopyTexSubImage1D
 * Signature: (IIIIII)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glCopyTexSubImage1D
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glCopyTexImage2D
 * Signature: (IIIIIIII)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glCopyTexImage2D
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glCopyTexImage1D
 * Signature: (IIIIIII)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glCopyTexImage1D
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glColorTableParameteriv
 * Signature: (IILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glColorTableParameteriv
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glColorTableParameterfv
 * Signature: (IILjava/nio/FloatBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glColorTableParameterfv
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glCopyColorSubTable
 * Signature: (IIIII)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glCopyColorSubTable
  (JNIEnv *, jclass, jint, jint, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glCopyColorTable
 * Signature: (IIIII)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glCopyColorTable
  (JNIEnv *, jclass, jint, jint, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glBlendEquation
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glBlendEquation
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glHistogram
 * Signature: (IIIZ)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glHistogram
  (JNIEnv *, jclass, jint, jint, jint, jboolean);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glResetHistogram
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glResetHistogram
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glGetHistogram
 * Signature: (IZIILjava/nio/Buffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glGetHistogram
  (JNIEnv *, jclass, jint, jboolean, jint, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glGetHistogramParameterfv
 * Signature: (IILjava/nio/FloatBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glGetHistogramParameterfv
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glGetHistogramParameteriv
 * Signature: (IILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glGetHistogramParameteriv
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glMinmax
 * Signature: (IIZ)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glMinmax
  (JNIEnv *, jclass, jint, jint, jboolean);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glResetMinmax
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glResetMinmax
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glGetMinmax
 * Signature: (IZIILjava/nio/Buffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glGetMinmax
  (JNIEnv *, jclass, jint, jboolean, jint, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glGetMinmaxParameterfv
 * Signature: (IILjava/nio/FloatBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glGetMinmaxParameterfv
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glGetMinmaxParameteriv
 * Signature: (IILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glGetMinmaxParameteriv
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glConvolutionFilter1D
 * Signature: (IIIIILjava/nio/Buffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glConvolutionFilter1D
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glConvolutionFilter2D
 * Signature: (IIIIIILjava/nio/Buffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glConvolutionFilter2D
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glConvolutionParameterf
 * Signature: (IIF)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glConvolutionParameterf
  (JNIEnv *, jclass, jint, jint, jfloat);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glConvolutionParameterfv
 * Signature: (IILjava/nio/FloatBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glConvolutionParameterfv
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glConvolutionParameteri
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glConvolutionParameteri
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glConvolutionParameteriv
 * Signature: (IILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glConvolutionParameteriv
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glCopyConvolutionFilter1D
 * Signature: (IIIII)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glCopyConvolutionFilter1D
  (JNIEnv *, jclass, jint, jint, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glCopyConvolutionFilter2D
 * Signature: (IIIIII)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glCopyConvolutionFilter2D
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glGetConvolutionFilter
 * Signature: (IIILjava/nio/Buffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glGetConvolutionFilter
  (JNIEnv *, jclass, jint, jint, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glGetConvolutionParameterfv
 * Signature: (IILjava/nio/FloatBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glGetConvolutionParameterfv
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glGetConvolutionParameteriv
 * Signature: (IILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glGetConvolutionParameteriv
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glSeparableFilter2D
 * Signature: (IIIIIILjava/nio/Buffer;Ljava/nio/Buffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glSeparableFilter2D
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jobject, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glGetSeparableFilter
 * Signature: (IIILjava/nio/Buffer;Ljava/nio/Buffer;Ljava/nio/Buffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glGetSeparableFilter
  (JNIEnv *, jclass, jint, jint, jint, jobject, jobject, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glDrawRangeElements
 * Signature: (IIIIILjava/nio/Buffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glDrawRangeElements
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glTexImage3D
 * Signature: (IIIIIIIIILjava/nio/Buffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glTexImage3D
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jint, jint, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glTexSubImage3D
 * Signature: (IIIIIIIIIILjava/nio/Buffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glTexSubImage3D
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glCopyTexSubImage3D
 * Signature: (IIIIIIIII)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glCopyTexSubImage3D
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glActiveTexture
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glActiveTexture
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glClientActiveTexture
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glClientActiveTexture
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glCompressedTexImage1D
 * Signature: (IIIIIILjava/nio/Buffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glCompressedTexImage1D
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glCompressedTexImage2D
 * Signature: (IIIIIIILjava/nio/Buffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glCompressedTexImage2D
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glCompressedTexImage3D
 * Signature: (IIIIIIIILjava/nio/Buffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glCompressedTexImage3D
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jint, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glCompressedTexSubImage1D
 * Signature: (IIIIIILjava/nio/Buffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glCompressedTexSubImage1D
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glCompressedTexSubImage2D
 * Signature: (IIIIIIIILjava/nio/Buffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glCompressedTexSubImage2D
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jint, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glCompressedTexSubImage3D
 * Signature: (IIIIIIIIIILjava/nio/Buffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glCompressedTexSubImage3D
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glGetCompressedTexImage
 * Signature: (IILjava/nio/Buffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glGetCompressedTexImage
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glMultiTexCoord1d
 * Signature: (ID)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glMultiTexCoord1d
  (JNIEnv *, jclass, jint, jdouble);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glMultiTexCoord1f
 * Signature: (IF)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glMultiTexCoord1f
  (JNIEnv *, jclass, jint, jfloat);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glMultiTexCoord1i
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glMultiTexCoord1i
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glMultiTexCoord1s
 * Signature: (IS)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glMultiTexCoord1s
  (JNIEnv *, jclass, jint, jshort);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glMultiTexCoord2d
 * Signature: (IDD)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glMultiTexCoord2d
  (JNIEnv *, jclass, jint, jdouble, jdouble);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glMultiTexCoord2f
 * Signature: (IFF)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glMultiTexCoord2f
  (JNIEnv *, jclass, jint, jfloat, jfloat);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glMultiTexCoord2i
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glMultiTexCoord2i
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glMultiTexCoord2s
 * Signature: (ISS)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glMultiTexCoord2s
  (JNIEnv *, jclass, jint, jshort, jshort);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glMultiTexCoord3d
 * Signature: (IDDD)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glMultiTexCoord3d
  (JNIEnv *, jclass, jint, jdouble, jdouble, jdouble);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glMultiTexCoord3f
 * Signature: (IFFF)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glMultiTexCoord3f
  (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glMultiTexCoord3i
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glMultiTexCoord3i
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glMultiTexCoord3s
 * Signature: (ISSS)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glMultiTexCoord3s
  (JNIEnv *, jclass, jint, jshort, jshort, jshort);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glMultiTexCoord4d
 * Signature: (IDDDD)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glMultiTexCoord4d
  (JNIEnv *, jclass, jint, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glMultiTexCoord4f
 * Signature: (IFFFF)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glMultiTexCoord4f
  (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glMultiTexCoord4i
 * Signature: (IIIII)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glMultiTexCoord4i
  (JNIEnv *, jclass, jint, jint, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glMultiTexCoord4s
 * Signature: (ISSSS)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glMultiTexCoord4s
  (JNIEnv *, jclass, jint, jshort, jshort, jshort, jshort);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glLoadTransposeMatrixd
 * Signature: (Ljava/nio/DoubleBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glLoadTransposeMatrixd
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glLoadTransposeMatrixf
 * Signature: (Ljava/nio/FloatBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glLoadTransposeMatrixf
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glMultTransposeMatrixd
 * Signature: (Ljava/nio/DoubleBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glMultTransposeMatrixd
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glMultTransposeMatrixf
 * Signature: (Ljava/nio/FloatBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glMultTransposeMatrixf
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glSampleCoverage
 * Signature: (FZ)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glSampleCoverage
  (JNIEnv *, jclass, jfloat, jboolean);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glCopyPixels
 * Signature: (IIIII)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glCopyPixels
  (JNIEnv *, jclass, jint, jint, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glColorPointer
 * Signature: (IIILjava/nio/Buffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glColorPointer
  (JNIEnv *, jclass, jint, jint, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glColorMaterial
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glColorMaterial
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glColorMask
 * Signature: (ZZZZ)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glColorMask
  (JNIEnv *, jclass, jboolean, jboolean, jboolean, jboolean);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glColor3b
 * Signature: (BBB)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glColor3b
  (JNIEnv *, jclass, jbyte, jbyte, jbyte);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glColor3d
 * Signature: (DDD)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glColor3d
  (JNIEnv *, jclass, jdouble, jdouble, jdouble);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glColor3f
 * Signature: (FFF)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glColor3f
  (JNIEnv *, jclass, jfloat, jfloat, jfloat);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glColor3i
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glColor3i
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glColor3s
 * Signature: (SSS)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glColor3s
  (JNIEnv *, jclass, jshort, jshort, jshort);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glColor3ub
 * Signature: (BBB)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glColor3ub
  (JNIEnv *, jclass, jbyte, jbyte, jbyte);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glColor3ui
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glColor3ui
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glColor3us
 * Signature: (SSS)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glColor3us
  (JNIEnv *, jclass, jshort, jshort, jshort);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glColor4b
 * Signature: (BBBB)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glColor4b
  (JNIEnv *, jclass, jbyte, jbyte, jbyte, jbyte);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glColor4d
 * Signature: (DDDD)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glColor4d
  (JNIEnv *, jclass, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glColor4f
 * Signature: (FFFF)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glColor4f
  (JNIEnv *, jclass, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glColor4i
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glColor4i
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glColor4s
 * Signature: (SSSS)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glColor4s
  (JNIEnv *, jclass, jshort, jshort, jshort, jshort);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glColor4ub
 * Signature: (BBBB)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glColor4ub
  (JNIEnv *, jclass, jbyte, jbyte, jbyte, jbyte);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glColor4ui
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glColor4ui
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glColor4us
 * Signature: (SSSS)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glColor4us
  (JNIEnv *, jclass, jshort, jshort, jshort, jshort);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glClipPlane
 * Signature: (ILjava/nio/DoubleBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glClipPlane
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glClearStencil
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glClearStencil
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glClearIndex
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glClearIndex
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glEvalPoint1
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glEvalPoint1
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glEvalPoint2
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glEvalPoint2
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glEvalMesh1
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glEvalMesh1
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glEvalMesh2
 * Signature: (IIIII)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glEvalMesh2
  (JNIEnv *, jclass, jint, jint, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glEvalCoord1d
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glEvalCoord1d
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glEvalCoord1f
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glEvalCoord1f
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glEvalCoord2d
 * Signature: (DD)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glEvalCoord2d
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glEvalCoord2f
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glEvalCoord2f
  (JNIEnv *, jclass, jfloat, jfloat);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glEnableClientState
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glEnableClientState
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glDisableClientState
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glDisableClientState
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glEnable
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glEnable
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glDisable
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glDisable
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glEdgeFlagPointer
 * Signature: (ILjava/nio/Buffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glEdgeFlagPointer
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glEdgeFlag
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glEdgeFlag
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glDrawPixels
 * Signature: (IIIILjava/nio/Buffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glDrawPixels
  (JNIEnv *, jclass, jint, jint, jint, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glDrawElements
 * Signature: (IIILjava/nio/Buffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glDrawElements
  (JNIEnv *, jclass, jint, jint, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glDrawBuffer
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glDrawBuffer
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glDrawArrays
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glDrawArrays
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glDepthRange
 * Signature: (DD)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glDepthRange
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glDepthMask
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glDepthMask
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glDepthFunc
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glDepthFunc
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glFeedbackBuffer
 * Signature: (IILjava/nio/FloatBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glFeedbackBuffer
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glGetPixelMapfv
 * Signature: (ILjava/nio/FloatBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glGetPixelMapfv
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glGetPixelMapuiv
 * Signature: (ILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glGetPixelMapuiv
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glGetPixelMapusv
 * Signature: (ILjava/nio/CharBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glGetPixelMapusv
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glGetMaterialfv
 * Signature: (IILjava/nio/FloatBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glGetMaterialfv
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glGetMaterialiv
 * Signature: (IILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glGetMaterialiv
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glGetMapdv
 * Signature: (IILjava/nio/DoubleBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glGetMapdv
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glGetMapfv
 * Signature: (IILjava/nio/FloatBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glGetMapfv
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glGetMapiv
 * Signature: (IILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glGetMapiv
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glGetLightfv
 * Signature: (IILjava/nio/FloatBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glGetLightfv
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glGetLightiv
 * Signature: (IILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glGetLightiv
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glGetError
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_lwjgl_opengl_CoreGL_glGetError
  (JNIEnv *, jclass);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glGetClipPlane
 * Signature: (ILjava/nio/DoubleBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glGetClipPlane
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glGetBooleanv
 * Signature: (ILjava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glGetBooleanv
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glGetDoublev
 * Signature: (ILjava/nio/DoubleBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glGetDoublev
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glGetFloatv
 * Signature: (ILjava/nio/FloatBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glGetFloatv
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glGetIntegerv
 * Signature: (ILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glGetIntegerv
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glGenTextures
 * Signature: (ILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glGenTextures
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glGenLists
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_lwjgl_opengl_CoreGL_glGenLists
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glFrustum
 * Signature: (DDDDDD)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glFrustum
  (JNIEnv *, jclass, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glFrontFace
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glFrontFace
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glFogf
 * Signature: (IF)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glFogf
  (JNIEnv *, jclass, jint, jfloat);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glFogi
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glFogi
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glFogfv
 * Signature: (ILjava/nio/FloatBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glFogfv
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glFogiv
 * Signature: (ILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glFogiv
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glFlush
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glFlush
  (JNIEnv *, jclass);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glFinish
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glFinish
  (JNIEnv *, jclass);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glGetPointerv
 * Signature: (II)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_org_lwjgl_opengl_CoreGL_glGetPointerv
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glIsEnabled
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_lwjgl_opengl_CoreGL_glIsEnabled
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glInterleavedArrays
 * Signature: (IILjava/nio/Buffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glInterleavedArrays
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glInitNames
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glInitNames
  (JNIEnv *, jclass);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glIndexPointer
 * Signature: (IILjava/nio/Buffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glIndexPointer
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glIndexMask
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glIndexMask
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glIndexd
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glIndexd
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glIndexf
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glIndexf
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glIndexi
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glIndexi
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glIndexs
 * Signature: (S)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glIndexs
  (JNIEnv *, jclass, jshort);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glIndexub
 * Signature: (B)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glIndexub
  (JNIEnv *, jclass, jbyte);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glHint
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glHint
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glGetTexParameterfv
 * Signature: (IILjava/nio/FloatBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glGetTexParameterfv
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glGetTexParameteriv
 * Signature: (IILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glGetTexParameteriv
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glGetTexLevelParameterfv
 * Signature: (IIILjava/nio/FloatBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glGetTexLevelParameterfv
  (JNIEnv *, jclass, jint, jint, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glGetTexLevelParameteriv
 * Signature: (IIILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glGetTexLevelParameteriv
  (JNIEnv *, jclass, jint, jint, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glGetTexImage
 * Signature: (IIIILjava/nio/Buffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glGetTexImage
  (JNIEnv *, jclass, jint, jint, jint, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glGetTexGendv
 * Signature: (IILjava/nio/DoubleBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glGetTexGendv
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glGetTexGenfv
 * Signature: (IILjava/nio/FloatBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glGetTexGenfv
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glGetTexGeniv
 * Signature: (IILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glGetTexGeniv
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glGetTexEnvfv
 * Signature: (IILjava/nio/FloatBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glGetTexEnvfv
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glGetTexEnviv
 * Signature: (IILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glGetTexEnviv
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glGetString
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_lwjgl_opengl_CoreGL_glGetString
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glGetPolygonStipple
 * Signature: (Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glGetPolygonStipple
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glIsList
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_lwjgl_opengl_CoreGL_glIsList
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glMaterialf
 * Signature: (IIF)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glMaterialf
  (JNIEnv *, jclass, jint, jint, jfloat);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glMateriali
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glMateriali
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glMaterialfv
 * Signature: (IILjava/nio/FloatBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glMaterialfv
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glMaterialiv
 * Signature: (IILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glMaterialiv
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glMapGrid1d
 * Signature: (IDD)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glMapGrid1d
  (JNIEnv *, jclass, jint, jdouble, jdouble);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glMapGrid1f
 * Signature: (IFF)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glMapGrid1f
  (JNIEnv *, jclass, jint, jfloat, jfloat);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glMapGrid2d
 * Signature: (IDDIDD)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glMapGrid2d
  (JNIEnv *, jclass, jint, jdouble, jdouble, jint, jdouble, jdouble);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glMapGrid2f
 * Signature: (IFFIFF)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glMapGrid2f
  (JNIEnv *, jclass, jint, jfloat, jfloat, jint, jfloat, jfloat);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glMap2d
 * Signature: (IDDIIDDIILjava/nio/DoubleBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glMap2d
  (JNIEnv *, jclass, jint, jdouble, jdouble, jint, jint, jdouble, jdouble, jint, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glMap2f
 * Signature: (IFFIIFFIILjava/nio/FloatBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glMap2f
  (JNIEnv *, jclass, jint, jfloat, jfloat, jint, jint, jfloat, jfloat, jint, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glMap1d
 * Signature: (IDDIILjava/nio/DoubleBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glMap1d
  (JNIEnv *, jclass, jint, jdouble, jdouble, jint, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glMap1f
 * Signature: (IFFIILjava/nio/FloatBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glMap1f
  (JNIEnv *, jclass, jint, jfloat, jfloat, jint, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glLogicOp
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glLogicOp
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glLoadName
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glLoadName
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glLoadMatrixd
 * Signature: (Ljava/nio/DoubleBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glLoadMatrixd
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glLoadMatrixf
 * Signature: (Ljava/nio/FloatBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glLoadMatrixf
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glLoadIdentity
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glLoadIdentity
  (JNIEnv *, jclass);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glListBase
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glListBase
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glLineWidth
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glLineWidth
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glLineStipple
 * Signature: (IS)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glLineStipple
  (JNIEnv *, jclass, jint, jshort);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glLightModelf
 * Signature: (IF)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glLightModelf
  (JNIEnv *, jclass, jint, jfloat);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glLightModeli
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glLightModeli
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glLightModelfv
 * Signature: (ILjava/nio/FloatBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glLightModelfv
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glLightModeliv
 * Signature: (ILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glLightModeliv
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glLightf
 * Signature: (IIF)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glLightf
  (JNIEnv *, jclass, jint, jint, jfloat);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glLighti
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glLighti
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glLightfv
 * Signature: (IILjava/nio/FloatBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glLightfv
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glLightiv
 * Signature: (IILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glLightiv
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glIsTexture
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_lwjgl_opengl_CoreGL_glIsTexture
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glMatrixMode
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glMatrixMode
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glPolygonStipple
 * Signature: (Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glPolygonStipple
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glPolygonOffset
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glPolygonOffset
  (JNIEnv *, jclass, jfloat, jfloat);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glPolygonMode
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glPolygonMode
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glPointSize
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glPointSize
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glPixelZoom
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glPixelZoom
  (JNIEnv *, jclass, jfloat, jfloat);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glPixelTransferf
 * Signature: (IF)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glPixelTransferf
  (JNIEnv *, jclass, jint, jfloat);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glPixelTransferi
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glPixelTransferi
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glPixelStoref
 * Signature: (IF)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glPixelStoref
  (JNIEnv *, jclass, jint, jfloat);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glPixelStorei
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glPixelStorei
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glPixelMapfv
 * Signature: (IILjava/nio/FloatBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glPixelMapfv
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glPixelMapuiv
 * Signature: (IILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glPixelMapuiv
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glPixelMapusv
 * Signature: (IILjava/nio/CharBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glPixelMapusv
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glPassThrough
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glPassThrough
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glOrtho
 * Signature: (DDDDDD)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glOrtho
  (JNIEnv *, jclass, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glNormalPointer
 * Signature: (IILjava/nio/Buffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glNormalPointer
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glNormal3b
 * Signature: (BBB)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glNormal3b
  (JNIEnv *, jclass, jbyte, jbyte, jbyte);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glNormal3d
 * Signature: (DDD)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glNormal3d
  (JNIEnv *, jclass, jdouble, jdouble, jdouble);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glNormal3f
 * Signature: (FFF)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glNormal3f
  (JNIEnv *, jclass, jfloat, jfloat, jfloat);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glNormal3i
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glNormal3i
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glNormal3s
 * Signature: (SSS)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glNormal3s
  (JNIEnv *, jclass, jshort, jshort, jshort);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glNewList
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glNewList
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glEndList
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glEndList
  (JNIEnv *, jclass);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glMultMatrixd
 * Signature: (Ljava/nio/DoubleBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glMultMatrixd
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glMultMatrixf
 * Signature: (Ljava/nio/FloatBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glMultMatrixf
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glPrioritizeTextures
 * Signature: (ILjava/nio/IntBuffer;Ljava/nio/FloatBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glPrioritizeTextures
  (JNIEnv *, jclass, jint, jobject, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glShadeModel
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glShadeModel
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glSelectBuffer
 * Signature: (ILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glSelectBuffer
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glScissor
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glScissor
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glScaled
 * Signature: (DDD)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glScaled
  (JNIEnv *, jclass, jdouble, jdouble, jdouble);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glScalef
 * Signature: (FFF)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glScalef
  (JNIEnv *, jclass, jfloat, jfloat, jfloat);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glRotated
 * Signature: (DDDD)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glRotated
  (JNIEnv *, jclass, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glRotatef
 * Signature: (FFFF)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glRotatef
  (JNIEnv *, jclass, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glRenderMode
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_lwjgl_opengl_CoreGL_glRenderMode
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glRectd
 * Signature: (DDDD)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glRectd
  (JNIEnv *, jclass, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glRectf
 * Signature: (FFFF)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glRectf
  (JNIEnv *, jclass, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glRecti
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glRecti
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glRects
 * Signature: (SSSS)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glRects
  (JNIEnv *, jclass, jshort, jshort, jshort, jshort);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glReadPixels
 * Signature: (IIIIIILjava/nio/Buffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glReadPixels
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glReadBuffer
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glReadBuffer
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glRasterPos2d
 * Signature: (DD)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glRasterPos2d
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glRasterPos2f
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glRasterPos2f
  (JNIEnv *, jclass, jfloat, jfloat);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glRasterPos2i
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glRasterPos2i
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glRasterPos2s
 * Signature: (SS)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glRasterPos2s
  (JNIEnv *, jclass, jshort, jshort);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glRasterPos3d
 * Signature: (DDD)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glRasterPos3d
  (JNIEnv *, jclass, jdouble, jdouble, jdouble);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glRasterPos3f
 * Signature: (FFF)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glRasterPos3f
  (JNIEnv *, jclass, jfloat, jfloat, jfloat);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glRasterPos3i
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glRasterPos3i
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glRasterPos3s
 * Signature: (SSS)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glRasterPos3s
  (JNIEnv *, jclass, jshort, jshort, jshort);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glRasterPos4d
 * Signature: (DDDD)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glRasterPos4d
  (JNIEnv *, jclass, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glRasterPos4f
 * Signature: (FFFF)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glRasterPos4f
  (JNIEnv *, jclass, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glRasterPos4i
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glRasterPos4i
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glRasterPos4s
 * Signature: (SSSS)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glRasterPos4s
  (JNIEnv *, jclass, jshort, jshort, jshort, jshort);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glPushName
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glPushName
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glPopName
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glPopName
  (JNIEnv *, jclass);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glPushMatrix
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glPushMatrix
  (JNIEnv *, jclass);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glPopMatrix
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glPopMatrix
  (JNIEnv *, jclass);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glPushClientAttrib
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glPushClientAttrib
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glPopClientAttrib
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glPopClientAttrib
  (JNIEnv *, jclass);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glPushAttrib
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glPushAttrib
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glPopAttrib
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glPopAttrib
  (JNIEnv *, jclass);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glStencilFunc
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glStencilFunc
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glVertexPointer
 * Signature: (IIILjava/nio/Buffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glVertexPointer
  (JNIEnv *, jclass, jint, jint, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glVertex2d
 * Signature: (DD)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glVertex2d
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glVertex2f
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glVertex2f
  (JNIEnv *, jclass, jfloat, jfloat);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glVertex2i
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glVertex2i
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glVertex2s
 * Signature: (SS)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glVertex2s
  (JNIEnv *, jclass, jshort, jshort);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glVertex3d
 * Signature: (DDD)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glVertex3d
  (JNIEnv *, jclass, jdouble, jdouble, jdouble);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glVertex3f
 * Signature: (FFF)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glVertex3f
  (JNIEnv *, jclass, jfloat, jfloat, jfloat);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glVertex3i
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glVertex3i
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glVertex3s
 * Signature: (SSS)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glVertex3s
  (JNIEnv *, jclass, jshort, jshort, jshort);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glVertex4d
 * Signature: (DDDD)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glVertex4d
  (JNIEnv *, jclass, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glVertex4f
 * Signature: (FFFF)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glVertex4f
  (JNIEnv *, jclass, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glVertex4i
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glVertex4i
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glVertex4s
 * Signature: (SSSS)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glVertex4s
  (JNIEnv *, jclass, jshort, jshort, jshort, jshort);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glTranslated
 * Signature: (DDD)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glTranslated
  (JNIEnv *, jclass, jdouble, jdouble, jdouble);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glTranslatef
 * Signature: (FFF)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glTranslatef
  (JNIEnv *, jclass, jfloat, jfloat, jfloat);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glTexSubImage2D
 * Signature: (IIIIIIIILjava/nio/Buffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glTexSubImage2D
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jint, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glTexSubImage1D
 * Signature: (IIIIIILjava/nio/Buffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glTexSubImage1D
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glTexParameterf
 * Signature: (IIF)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glTexParameterf
  (JNIEnv *, jclass, jint, jint, jfloat);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glTexParameteri
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glTexParameteri
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glTexImage2D
 * Signature: (IIIIIIIILjava/nio/Buffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glTexImage2D
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jint, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glTexImage1D
 * Signature: (IIIIIIILjava/nio/Buffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glTexImage1D
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glTexGend
 * Signature: (IID)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glTexGend
  (JNIEnv *, jclass, jint, jint, jdouble);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glTexGenf
 * Signature: (IIF)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glTexGenf
  (JNIEnv *, jclass, jint, jint, jfloat);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glTexGeni
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glTexGeni
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glTexGendv
 * Signature: (IILjava/nio/DoubleBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glTexGendv
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glTexGenfv
 * Signature: (IILjava/nio/FloatBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glTexGenfv
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glTexGeniv
 * Signature: (IILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glTexGeniv
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glTexEnvf
 * Signature: (IIF)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glTexEnvf
  (JNIEnv *, jclass, jint, jint, jfloat);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glTexEnvi
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glTexEnvi
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glTexEnvfv
 * Signature: (IILjava/nio/FloatBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glTexEnvfv
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glTexEnviv
 * Signature: (IILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glTexEnviv
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glTexCoordPointer
 * Signature: (IIILjava/nio/Buffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glTexCoordPointer
  (JNIEnv *, jclass, jint, jint, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glTexCoord1d
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glTexCoord1d
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glTexCoord1f
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glTexCoord1f
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glTexCoord1i
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glTexCoord1i
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glTexCoord1s
 * Signature: (S)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glTexCoord1s
  (JNIEnv *, jclass, jshort);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glTexCoord2d
 * Signature: (DD)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glTexCoord2d
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glTexCoord2f
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glTexCoord2f
  (JNIEnv *, jclass, jfloat, jfloat);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glTexCoord2i
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glTexCoord2i
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glTexCoord2s
 * Signature: (SS)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glTexCoord2s
  (JNIEnv *, jclass, jshort, jshort);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glTexCoord3d
 * Signature: (DDD)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glTexCoord3d
  (JNIEnv *, jclass, jdouble, jdouble, jdouble);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glTexCoord3f
 * Signature: (FFF)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glTexCoord3f
  (JNIEnv *, jclass, jfloat, jfloat, jfloat);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glTexCoord3i
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glTexCoord3i
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glTexCoord3s
 * Signature: (SSS)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glTexCoord3s
  (JNIEnv *, jclass, jshort, jshort, jshort);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glTexCoord4d
 * Signature: (DDDD)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glTexCoord4d
  (JNIEnv *, jclass, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glTexCoord4f
 * Signature: (FFFF)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glTexCoord4f
  (JNIEnv *, jclass, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glTexCoord4i
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glTexCoord4i
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glTexCoord4s
 * Signature: (SSSS)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glTexCoord4s
  (JNIEnv *, jclass, jshort, jshort, jshort, jshort);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glStencilOp
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glStencilOp
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glStencilMask
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glStencilMask
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glViewport
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glViewport
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    glMultiDrawArrays
 * Signature: (ILjava/nio/ByteBuffer;Ljava/nio/ByteBuffer;I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_glMultiDrawArrays
  (JNIEnv *, jclass, jint, jobject, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
