/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_lwjgl_opengl_CoreGL */

#ifndef _Included_org_lwjgl_opengl_CoreGL
#define _Included_org_lwjgl_opengl_CoreGL
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: _00024assertionsDisabled */
/* Inaccessible static: currentContext */
/* Inaccessible static: class_000240 */
/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    accum
 * Signature: (IF)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_accum
  (JNIEnv *, jobject, jint, jfloat);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    alphaFunc
 * Signature: (IF)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_alphaFunc
  (JNIEnv *, jobject, jint, jfloat);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    colorTable
 * Signature: (IIIIII)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_colorTable
  (JNIEnv *, jobject, jint, jint, jint, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    colorSubTable
 * Signature: (IIIIII)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_colorSubTable
  (JNIEnv *, jobject, jint, jint, jint, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    getColorTable
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_getColorTable
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    getColorTableParameteriv
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_getColorTableParameteriv
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    getColorTableParameterfv
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_getColorTableParameterfv
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    clearColor
 * Signature: (FFFF)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_clearColor
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    clearAccum
 * Signature: (FFFF)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_clearAccum
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    clear
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_clear
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    callLists
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_callLists
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    callList
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_callList
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    blendFunc
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_blendFunc
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    blendColor
 * Signature: (FFFF)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_blendColor
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    bitmap
 * Signature: (IIFFFFI)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_bitmap
  (JNIEnv *, jobject, jint, jint, jfloat, jfloat, jfloat, jfloat, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    bindTexture
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_bindTexture
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    begin
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_begin
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    end
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_end
  (JNIEnv *, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    arrayElement
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_arrayElement
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    areTexturesResident
 * Signature: (III)Z
 */
JNIEXPORT jboolean JNICALL Java_org_lwjgl_opengl_CoreGL_areTexturesResident
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    clearDepth
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_clearDepth
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    deleteLists
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_deleteLists
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    deleteTextures
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_deleteTextures
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    cullFace
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_cullFace
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    copyTexSubImage2D
 * Signature: (IIIIIIII)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_copyTexSubImage2D
  (JNIEnv *, jobject, jint, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    copyTexSubImage1D
 * Signature: (IIIIII)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_copyTexSubImage1D
  (JNIEnv *, jobject, jint, jint, jint, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    copyTexImage2D
 * Signature: (IIIIIIII)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_copyTexImage2D
  (JNIEnv *, jobject, jint, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    copyTexImage1D
 * Signature: (IIIIIII)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_copyTexImage1D
  (JNIEnv *, jobject, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    copyPixels
 * Signature: (IIIII)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_copyPixels
  (JNIEnv *, jobject, jint, jint, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    colorPointer
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_colorPointer
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    colorMaterial
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_colorMaterial
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    colorMask
 * Signature: (ZZZZ)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_colorMask
  (JNIEnv *, jobject, jboolean, jboolean, jboolean, jboolean);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    color3b
 * Signature: (BBB)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_color3b
  (JNIEnv *, jobject, jbyte, jbyte, jbyte);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    color3d
 * Signature: (DDD)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_color3d
  (JNIEnv *, jobject, jdouble, jdouble, jdouble);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    color3f
 * Signature: (FFF)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_color3f
  (JNIEnv *, jobject, jfloat, jfloat, jfloat);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    color3i
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_color3i
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    color3s
 * Signature: (SSS)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_color3s
  (JNIEnv *, jobject, jshort, jshort, jshort);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    color3ub
 * Signature: (BBB)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_color3ub
  (JNIEnv *, jobject, jbyte, jbyte, jbyte);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    color3ui
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_color3ui
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    color3us
 * Signature: (SSS)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_color3us
  (JNIEnv *, jobject, jshort, jshort, jshort);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    color4b
 * Signature: (BBBB)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_color4b
  (JNIEnv *, jobject, jbyte, jbyte, jbyte, jbyte);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    color4d
 * Signature: (DDDD)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_color4d
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    color4f
 * Signature: (FFFF)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_color4f
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    color4i
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_color4i
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    color4s
 * Signature: (SSSS)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_color4s
  (JNIEnv *, jobject, jshort, jshort, jshort, jshort);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    color4ub
 * Signature: (BBBB)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_color4ub
  (JNIEnv *, jobject, jbyte, jbyte, jbyte, jbyte);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    color4ui
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_color4ui
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    color4us
 * Signature: (SSSS)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_color4us
  (JNIEnv *, jobject, jshort, jshort, jshort, jshort);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    clipPlane
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_clipPlane
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    clearStencil
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_clearStencil
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    clearIndex
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_clearIndex
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    evalPoint1
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_evalPoint1
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    evalPoint2
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_evalPoint2
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    evalMesh1
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_evalMesh1
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    evalMesh2
 * Signature: (IIIII)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_evalMesh2
  (JNIEnv *, jobject, jint, jint, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    evalCoord1d
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_evalCoord1d
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    evalCoord1f
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_evalCoord1f
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    evalCoord2d
 * Signature: (DD)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_evalCoord2d
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    evalCoord2f
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_evalCoord2f
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    evalCoord1dv
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_evalCoord1dv
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    evalCoord1fv
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_evalCoord1fv
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    evalCoord2dv
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_evalCoord2dv
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    evalCoord2fv
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_evalCoord2fv
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    enableClientState
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_enableClientState
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    disableClientState
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_disableClientState
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    enable
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_enable
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    disable
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_disable
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    edgeFlagPointer
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_edgeFlagPointer
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    edgeFlag
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_edgeFlag
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    edgeFlagv
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_edgeFlagv
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    drawPixels
 * Signature: (IIIII)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_drawPixels
  (JNIEnv *, jobject, jint, jint, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    drawElements
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_drawElements
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    drawBuffer
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_drawBuffer
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    drawArrays
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_drawArrays
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    depthRange
 * Signature: (DD)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_depthRange
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    depthMask
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_depthMask
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    depthFunc
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_depthFunc
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    feedbackBuffer
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_feedbackBuffer
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    getPixelMapfv
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_getPixelMapfv
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    getPixelMapuiv
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_getPixelMapuiv
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    getPixelMapusv
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_getPixelMapusv
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    getMaterialfv
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_getMaterialfv
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    getMaterialiv
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_getMaterialiv
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    getMapdv
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_getMapdv
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    getMapfv
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_getMapfv
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    getMapiv
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_getMapiv
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    getLightfv
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_getLightfv
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    getLightiv
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_getLightiv
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    getError
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_lwjgl_opengl_CoreGL_getError
  (JNIEnv *, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    getClipPlane
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_getClipPlane
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    getBooleanv
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_getBooleanv
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    getDoublev
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_getDoublev
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    getFloatv
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_getFloatv
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    getIntegerv
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_getIntegerv
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    genTextures
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_genTextures
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    genLists
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_lwjgl_opengl_CoreGL_genLists
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    frustum
 * Signature: (DDDDDD)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_frustum
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    frontFace
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_frontFace
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    fogf
 * Signature: (IF)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_fogf
  (JNIEnv *, jobject, jint, jfloat);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    fogi
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_fogi
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    fogfv
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_fogfv
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    fogiv
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_fogiv
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    flush
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_flush
  (JNIEnv *, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    finish
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_finish
  (JNIEnv *, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    getPointerv
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_getPointerv
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    isEnabled
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_lwjgl_opengl_CoreGL_isEnabled
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    interleavedArrays
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_interleavedArrays
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    initNames
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_initNames
  (JNIEnv *, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    indexPointer
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_indexPointer
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    indexMask
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_indexMask
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    indexd
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_indexd
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    indexf
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_indexf
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    indexi
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_indexi
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    indexs
 * Signature: (S)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_indexs
  (JNIEnv *, jobject, jshort);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    indexub
 * Signature: (B)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_indexub
  (JNIEnv *, jobject, jbyte);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    indexdv
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_indexdv
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    indexfv
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_indexfv
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    indexiv
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_indexiv
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    indexsv
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_indexsv
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    indexubv
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_indexubv
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    hint
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_hint
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    getTexParameterfv
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_getTexParameterfv
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    getTexParameteriv
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_getTexParameteriv
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    getTexLevelParameterfv
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_getTexLevelParameterfv
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    getTexLevelParameteriv
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_getTexLevelParameteriv
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    getTexImage
 * Signature: (IIIII)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_getTexImage
  (JNIEnv *, jobject, jint, jint, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    getTexGendv
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_getTexGendv
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    getTexGenfv
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_getTexGenfv
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    getTexGeniv
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_getTexGeniv
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    getTexEnvfv
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_getTexEnvfv
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    getTexEnviv
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_getTexEnviv
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    getString
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_lwjgl_opengl_CoreGL_getString
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    getPolygonStipple
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_getPolygonStipple
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    isList
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_lwjgl_opengl_CoreGL_isList
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    materialf
 * Signature: (IIF)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_materialf
  (JNIEnv *, jobject, jint, jint, jfloat);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    materiali
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_materiali
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    materialfv
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_materialfv
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    materialiv
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_materialiv
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    mapGrid1d
 * Signature: (IDD)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_mapGrid1d
  (JNIEnv *, jobject, jint, jdouble, jdouble);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    mapGrid1f
 * Signature: (IFF)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_mapGrid1f
  (JNIEnv *, jobject, jint, jfloat, jfloat);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    mapGrid2d
 * Signature: (IDDIDD)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_mapGrid2d
  (JNIEnv *, jobject, jint, jdouble, jdouble, jint, jdouble, jdouble);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    mapGrid2f
 * Signature: (IFFIFF)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_mapGrid2f
  (JNIEnv *, jobject, jint, jfloat, jfloat, jint, jfloat, jfloat);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    map2d
 * Signature: (IDDIIDDIII)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_map2d
  (JNIEnv *, jobject, jint, jdouble, jdouble, jint, jint, jdouble, jdouble, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    map2f
 * Signature: (IFFIIFFIII)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_map2f
  (JNIEnv *, jobject, jint, jfloat, jfloat, jint, jint, jfloat, jfloat, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    map1d
 * Signature: (IDDIII)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_map1d
  (JNIEnv *, jobject, jint, jdouble, jdouble, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    map1f
 * Signature: (IFFIII)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_map1f
  (JNIEnv *, jobject, jint, jfloat, jfloat, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    logicOp
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_logicOp
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    loadName
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_loadName
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    loadMatrixd
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_loadMatrixd
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    loadMatrixf
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_loadMatrixf
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    loadIdentity
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_loadIdentity
  (JNIEnv *, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    listBase
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_listBase
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    lineWidth
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_lineWidth
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    lineStipple
 * Signature: (IS)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_lineStipple
  (JNIEnv *, jobject, jint, jshort);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    lightModelf
 * Signature: (IF)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_lightModelf
  (JNIEnv *, jobject, jint, jfloat);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    lightModeli
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_lightModeli
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    lightModelfv
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_lightModelfv
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    lightModeliv
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_lightModeliv
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    lightf
 * Signature: (IIF)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_lightf
  (JNIEnv *, jobject, jint, jint, jfloat);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    lighti
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_lighti
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    lightfv
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_lightfv
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    lightiv
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_lightiv
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    isTexture
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_lwjgl_opengl_CoreGL_isTexture
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    matrixMode
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_matrixMode
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    polygonStipple
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_polygonStipple
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    polygonOffset
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_polygonOffset
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    polygonMode
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_polygonMode
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    pointSize
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_pointSize
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    pixelZoom
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_pixelZoom
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    pixelTransferf
 * Signature: (IF)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_pixelTransferf
  (JNIEnv *, jobject, jint, jfloat);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    pixelTransferi
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_pixelTransferi
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    pixelStoref
 * Signature: (IF)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_pixelStoref
  (JNIEnv *, jobject, jint, jfloat);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    pixelStorei
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_pixelStorei
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    pixelMapfv
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_pixelMapfv
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    pixelMapuiv
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_pixelMapuiv
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    pixelMapusv
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_pixelMapusv
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    passThrough
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_passThrough
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    ortho
 * Signature: (DDDDDD)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_ortho
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    normalPointer
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_normalPointer
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    normal3b
 * Signature: (BBB)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_normal3b
  (JNIEnv *, jobject, jbyte, jbyte, jbyte);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    normal3d
 * Signature: (DDD)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_normal3d
  (JNIEnv *, jobject, jdouble, jdouble, jdouble);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    normal3f
 * Signature: (FFF)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_normal3f
  (JNIEnv *, jobject, jfloat, jfloat, jfloat);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    normal3i
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_normal3i
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    normal3s
 * Signature: (SSS)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_normal3s
  (JNIEnv *, jobject, jshort, jshort, jshort);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    normal3bv
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_normal3bv
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    normal3dv
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_normal3dv
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    normal3fv
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_normal3fv
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    normal3iv
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_normal3iv
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    normal3sv
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_normal3sv
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    newList
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_newList
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    endList
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_endList
  (JNIEnv *, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    multMatrixd
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_multMatrixd
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    multMatrixf
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_multMatrixf
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    prioritizeTextures
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_prioritizeTextures
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    shadeModel
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_shadeModel
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    selectBuffer
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_selectBuffer
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    scissor
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_scissor
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    scaled
 * Signature: (DDD)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_scaled
  (JNIEnv *, jobject, jdouble, jdouble, jdouble);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    scalef
 * Signature: (FFF)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_scalef
  (JNIEnv *, jobject, jfloat, jfloat, jfloat);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    rotated
 * Signature: (DDDD)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_rotated
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    rotatef
 * Signature: (FFFF)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_rotatef
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    renderMode
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_lwjgl_opengl_CoreGL_renderMode
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    rectd
 * Signature: (DDDD)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_rectd
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    rectf
 * Signature: (FFFF)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_rectf
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    recti
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_recti
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    rects
 * Signature: (SSSS)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_rects
  (JNIEnv *, jobject, jshort, jshort, jshort, jshort);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    rectdv
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_rectdv
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    rectfv
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_rectfv
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    rectiv
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_rectiv
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    rectsv
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_rectsv
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    readPixels
 * Signature: (IIIIIII)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_readPixels
  (JNIEnv *, jobject, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    readBuffer
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_readBuffer
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    rasterPos2d
 * Signature: (DD)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_rasterPos2d
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    rasterPos2f
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_rasterPos2f
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    rasterPos2i
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_rasterPos2i
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    rasterPos2s
 * Signature: (SS)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_rasterPos2s
  (JNIEnv *, jobject, jshort, jshort);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    rasterPos3d
 * Signature: (DDD)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_rasterPos3d
  (JNIEnv *, jobject, jdouble, jdouble, jdouble);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    rasterPos3f
 * Signature: (FFF)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_rasterPos3f
  (JNIEnv *, jobject, jfloat, jfloat, jfloat);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    rasterPos3i
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_rasterPos3i
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    rasterPos3s
 * Signature: (SSS)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_rasterPos3s
  (JNIEnv *, jobject, jshort, jshort, jshort);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    rasterPos4d
 * Signature: (DDDD)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_rasterPos4d
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    rasterPos4f
 * Signature: (FFFF)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_rasterPos4f
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    rasterPos4i
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_rasterPos4i
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    rasterPos4s
 * Signature: (SSSS)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_rasterPos4s
  (JNIEnv *, jobject, jshort, jshort, jshort, jshort);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    rasterPos2dv
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_rasterPos2dv
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    rasterPos2fv
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_rasterPos2fv
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    rasterPos2iv
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_rasterPos2iv
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    rasterPos2sv
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_rasterPos2sv
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    rasterPos3dv
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_rasterPos3dv
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    rasterPos3fv
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_rasterPos3fv
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    rasterPos3iv
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_rasterPos3iv
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    rasterPos3sv
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_rasterPos3sv
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    rasterPos4dv
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_rasterPos4dv
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    rasterPos4fv
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_rasterPos4fv
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    rasterPos4iv
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_rasterPos4iv
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    rasterPos4sv
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_rasterPos4sv
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    pushName
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_pushName
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    popName
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_popName
  (JNIEnv *, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    pushMatrix
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_pushMatrix
  (JNIEnv *, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    popMatrix
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_popMatrix
  (JNIEnv *, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    pushClientAttrib
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_pushClientAttrib
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    popClientAttrib
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_popClientAttrib
  (JNIEnv *, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    pushAttrib
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_pushAttrib
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    popAttrib
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_popAttrib
  (JNIEnv *, jobject);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    stencilFunc
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_stencilFunc
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    vertexPointer
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_vertexPointer
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    vertex2d
 * Signature: (DD)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_vertex2d
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    vertex2f
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_vertex2f
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    vertex2i
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_vertex2i
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    vertex2s
 * Signature: (SS)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_vertex2s
  (JNIEnv *, jobject, jshort, jshort);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    vertex3d
 * Signature: (DDD)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_vertex3d
  (JNIEnv *, jobject, jdouble, jdouble, jdouble);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    vertex3f
 * Signature: (FFF)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_vertex3f
  (JNIEnv *, jobject, jfloat, jfloat, jfloat);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    vertex3i
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_vertex3i
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    vertex3s
 * Signature: (SSS)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_vertex3s
  (JNIEnv *, jobject, jshort, jshort, jshort);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    vertex4d
 * Signature: (DDDD)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_vertex4d
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    vertex4f
 * Signature: (FFFF)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_vertex4f
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    vertex4i
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_vertex4i
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    vertex4s
 * Signature: (SSSS)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_vertex4s
  (JNIEnv *, jobject, jshort, jshort, jshort, jshort);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    vertex2dv
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_vertex2dv
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    vertex2fv
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_vertex2fv
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    vertex2iv
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_vertex2iv
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    vertex2sv
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_vertex2sv
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    vertex3dv
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_vertex3dv
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    vertex3fv
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_vertex3fv
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    vertex3iv
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_vertex3iv
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    vertex3sv
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_vertex3sv
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    vertex4dv
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_vertex4dv
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    vertex4fv
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_vertex4fv
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    vertex4iv
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_vertex4iv
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    vertex4sv
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_vertex4sv
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    translated
 * Signature: (DDD)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_translated
  (JNIEnv *, jobject, jdouble, jdouble, jdouble);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    translatef
 * Signature: (FFF)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_translatef
  (JNIEnv *, jobject, jfloat, jfloat, jfloat);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    texSubImage2D
 * Signature: (IIIIIIIII)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_texSubImage2D
  (JNIEnv *, jobject, jint, jint, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    texSubImage1D
 * Signature: (IIIIIII)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_texSubImage1D
  (JNIEnv *, jobject, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    texParameterf
 * Signature: (IIF)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_texParameterf
  (JNIEnv *, jobject, jint, jint, jfloat);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    texParameteri
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_texParameteri
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    texImage2D
 * Signature: (IIIIIIIII)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_texImage2D
  (JNIEnv *, jobject, jint, jint, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    texImage1D
 * Signature: (IIIIIIII)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_texImage1D
  (JNIEnv *, jobject, jint, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    texGend
 * Signature: (IID)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_texGend
  (JNIEnv *, jobject, jint, jint, jdouble);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    texGenf
 * Signature: (IIF)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_texGenf
  (JNIEnv *, jobject, jint, jint, jfloat);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    texGeni
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_texGeni
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    texGendv
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_texGendv
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    texGenfv
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_texGenfv
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    texGeniv
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_texGeniv
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    texEnvf
 * Signature: (IIF)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_texEnvf
  (JNIEnv *, jobject, jint, jint, jfloat);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    texEnvi
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_texEnvi
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    texEnvfv
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_texEnvfv
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    texEnviv
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_texEnviv
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    texCoordPointer
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_texCoordPointer
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    texCoord1d
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_texCoord1d
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    texCoord1f
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_texCoord1f
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    texCoord1i
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_texCoord1i
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    texCoord1s
 * Signature: (S)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_texCoord1s
  (JNIEnv *, jobject, jshort);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    texCoord2d
 * Signature: (DD)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_texCoord2d
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    texCoord2f
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_texCoord2f
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    texCoord2i
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_texCoord2i
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    texCoord2s
 * Signature: (SS)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_texCoord2s
  (JNIEnv *, jobject, jshort, jshort);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    texCoord3d
 * Signature: (DDD)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_texCoord3d
  (JNIEnv *, jobject, jdouble, jdouble, jdouble);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    texCoord3f
 * Signature: (FFF)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_texCoord3f
  (JNIEnv *, jobject, jfloat, jfloat, jfloat);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    texCoord3i
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_texCoord3i
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    texCoord3s
 * Signature: (SSS)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_texCoord3s
  (JNIEnv *, jobject, jshort, jshort, jshort);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    texCoord4d
 * Signature: (DDDD)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_texCoord4d
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    texCoord4f
 * Signature: (FFFF)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_texCoord4f
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    texCoord4i
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_texCoord4i
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    texCoord4s
 * Signature: (SSSS)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_texCoord4s
  (JNIEnv *, jobject, jshort, jshort, jshort, jshort);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    texCoord1dv
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_texCoord1dv
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    texCoord1fv
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_texCoord1fv
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    texCoord1iv
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_texCoord1iv
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    texCoord1sv
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_texCoord1sv
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    texCoord2dv
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_texCoord2dv
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    texCoord2fv
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_texCoord2fv
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    texCoord2iv
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_texCoord2iv
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    texCoord2sv
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_texCoord2sv
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    texCoord3dv
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_texCoord3dv
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    texCoord3fv
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_texCoord3fv
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    texCoord3iv
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_texCoord3iv
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    texCoord3sv
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_texCoord3sv
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    texCoord4dv
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_texCoord4dv
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    texCoord4fv
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_texCoord4fv
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    texCoord4iv
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_texCoord4iv
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    texCoord4sv
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_texCoord4sv
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    stencilOp
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_stencilOp
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    stencilMask
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_stencilMask
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_CoreGL
 * Method:    viewport
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_CoreGL_viewport
  (JNIEnv *, jobject, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
