/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_lwjgl_opengl_GLU */

#ifndef _Included_org_lwjgl_opengl_GLU
#define _Included_org_lwjgl_opengl_GLU
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
