/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_lwjgl_Audio */

#ifndef _Included_org_lwjgl_Audio
#define _Included_org_lwjgl_Audio
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
