/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_lwjgl_opengl_GLContext */

#ifndef _Included_org_lwjgl_opengl_GLContext
#define _Included_org_lwjgl_opengl_GLContext
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: currentContext */
/* Inaccessible static: GL_ARB_imaging */
/* Inaccessible static: GL_ARB_depth_texture */
/* Inaccessible static: GL_ARB_fragment_program */
/* Inaccessible static: GL_ARB_fragment_shader */
/* Inaccessible static: GL_ARB_matrix_palette */
/* Inaccessible static: GL_ARB_multisample */
/* Inaccessible static: GL_ARB_multitexture */
/* Inaccessible static: GL_ARB_occlusion_query */
/* Inaccessible static: GL_ARB_point_parameters */
/* Inaccessible static: GL_ARB_point_sprite */
/* Inaccessible static: GL_ARB_shading_language */
/* Inaccessible static: GL_ARB_shader_objects */
/* Inaccessible static: GL_ARB_shadow */
/* Inaccessible static: GL_ARB_shadow_ambient */
/* Inaccessible static: GL_ARB_texture_compression */
/* Inaccessible static: GL_ARB_texture_env_add */
/* Inaccessible static: GL_ARB_texture_env_dot3 */
/* Inaccessible static: GL_ARB_texture_env_combine */
/* Inaccessible static: GL_ARB_texture_env_crossbar */
/* Inaccessible static: GL_ARB_texture_border_clamp */
/* Inaccessible static: GL_ARB_texture_cube_map */
/* Inaccessible static: GL_ARB_texture_mirrored_repeat */
/* Inaccessible static: GL_ARB_texture_non_power_of_two */
/* Inaccessible static: GL_ARB_transpose_matrix */
/* Inaccessible static: GL_ARB_vertex_blend */
/* Inaccessible static: GL_ARB_vertex_program */
/* Inaccessible static: GL_ARB_vertex_buffer_object */
/* Inaccessible static: GL_ARB_vertex_shader */
/* Inaccessible static: GL_ARB_window_pos */
/* Inaccessible static: GL_EXT_abgr */
/* Inaccessible static: GL_EXT_bgra */
/* Inaccessible static: GL_EXT_blend_function_separate */
/* Inaccessible static: GL_EXT_blend_subtract */
/* Inaccessible static: GL_EXT_compiled_vertex_array */
/* Inaccessible static: GL_EXT_draw_range_elements */
/* Inaccessible static: GL_EXT_multi_draw_arrays */
/* Inaccessible static: GL_EXT_fog_coord */
/* Inaccessible static: GL_EXT_packed_pixels */
/* Inaccessible static: GL_EXT_point_parameters */
/* Inaccessible static: GL_EXT_rescale_normal */
/* Inaccessible static: GL_EXT_secondary_color */
/* Inaccessible static: GL_EXT_separate_specular_color */
/* Inaccessible static: GL_EXT_shadow_funcs */
/* Inaccessible static: GL_EXT_shared_texture_palette */
/* Inaccessible static: GL_EXT_stencil_two_side */
/* Inaccessible static: GL_EXT_stencil_wrap */
/* Inaccessible static: GL_EXT_texture_compression_s3tc */
/* Inaccessible static: GL_EXT_texture_env_combine */
/* Inaccessible static: GL_EXT_texture_env_dot3 */
/* Inaccessible static: GL_EXT_texture_filter_anisotropic */
/* Inaccessible static: GL_EXT_texture_lod_bias */
/* Inaccessible static: GL_EXT_texture_rectangle */
/* Inaccessible static: GL_EXT_vertex_shader */
/* Inaccessible static: GL_EXT_vertex_weighting */
/* Inaccessible static: GL_ATI_draw_buffers */
/* Inaccessible static: GL_ATI_element_array */
/* Inaccessible static: GL_ATI_envmap_bumpmap */
/* Inaccessible static: GL_ATI_fragment_shader */
/* Inaccessible static: GL_ATI_map_object_buffer */
/* Inaccessible static: GL_ATI_pn_triangles */
/* Inaccessible static: GL_ATI_texture_float */
/* Inaccessible static: GL_ATI_texture_mirror_once */
/* Inaccessible static: GL_ATI_vertex_array_object */
/* Inaccessible static: GL_ATI_vertex_attrib_array_object */
/* Inaccessible static: GL_ATI_vertex_streams */
/* Inaccessible static: GL_ATI_separate_stencil */
/* Inaccessible static: GL_NV_blend_square */
/* Inaccessible static: GL_NV_copy_depth_to_color */
/* Inaccessible static: GL_NV_depth_clamp */
/* Inaccessible static: GL_NV_evaluators */
/* Inaccessible static: GL_NV_fence */
/* Inaccessible static: GL_NV_fragment_program */
/* Inaccessible static: GL_NV_float_buffer */
/* Inaccessible static: GL_NV_fog_distance */
/* Inaccessible static: GL_NV_half_float */
/* Inaccessible static: GL_NV_light_max_exponent */
/* Inaccessible static: GL_NV_multisample_filter_hint */
/* Inaccessible static: GL_NV_occlusion_query */
/* Inaccessible static: GL_NV_packed_depth_stencil */
/* Inaccessible static: GL_NV_pixel_data_range */
/* Inaccessible static: GL_NV_point_sprite */
/* Inaccessible static: GL_NV_primitive_restart */
/* Inaccessible static: GL_NV_register_combiners */
/* Inaccessible static: GL_NV_register_combiners2 */
/* Inaccessible static: GL_NV_texgen_reflection */
/* Inaccessible static: GL_NV_texture_compression_vtc */
/* Inaccessible static: GL_NV_texture_env_combine4 */
/* Inaccessible static: GL_NV_texture_expand_normal */
/* Inaccessible static: GL_NV_texture_rectangle */
/* Inaccessible static: GL_NV_texture_shader */
/* Inaccessible static: GL_NV_texture_shader2 */
/* Inaccessible static: GL_NV_texture_shader3 */
/* Inaccessible static: GL_NV_vertex_array_range */
/* Inaccessible static: GL_NV_vertex_array_range2 */
/* Inaccessible static: GL_NV_vertex_program */
/* Inaccessible static: GL_NV_vertex_program1_1 */
/* Inaccessible static: GL_NV_vertex_program2 */
/* Inaccessible static: OpenGL11 */
/* Inaccessible static: OpenGL12 */
/* Inaccessible static: OpenGL13 */
/* Inaccessible static: OpenGL14 */
/* Inaccessible static: OpenGL15 */
/* Inaccessible static: class_000240 */
/* Inaccessible static: class_000241 */
/*
 * Class:     org_lwjgl_opengl_GLContext
 * Method:    init
 * Signature: (Ljava/util/Set;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GLContext_init
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
