/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_lwjgl_fmod_FMusic */

#ifndef _Included_org_lwjgl_fmod_FMusic
#define _Included_org_lwjgl_fmod_FMusic
#ifdef __cplusplus
extern "C" {
#endif
#undef org_lwjgl_fmod_FMusic_FMUSIC_TYPE_NONE
#define org_lwjgl_fmod_FMusic_FMUSIC_TYPE_NONE 0L
#undef org_lwjgl_fmod_FMusic_FMUSIC_TYPE_MOD
#define org_lwjgl_fmod_FMusic_FMUSIC_TYPE_MOD 1L
#undef org_lwjgl_fmod_FMusic_FMUSIC_TYPE_S3M
#define org_lwjgl_fmod_FMusic_FMUSIC_TYPE_S3M 2L
#undef org_lwjgl_fmod_FMusic_FMUSIC_TYPE_XM
#define org_lwjgl_fmod_FMusic_FMUSIC_TYPE_XM 3L
#undef org_lwjgl_fmod_FMusic_FMUSIC_TYPE_IT
#define org_lwjgl_fmod_FMusic_FMUSIC_TYPE_IT 4L
#undef org_lwjgl_fmod_FMusic_FMUSIC_TYPE_MIDI
#define org_lwjgl_fmod_FMusic_FMUSIC_TYPE_MIDI 5L
#undef org_lwjgl_fmod_FMusic_FMUSIC_TYPE_FSB
#define org_lwjgl_fmod_FMusic_FMUSIC_TYPE_FSB 6L
/*
 * Class:     org_lwjgl_fmod_FMusic
 * Method:    nFMUSIC_LoadSong
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_lwjgl_fmod_FMusic_nFMUSIC_1LoadSong
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_lwjgl_fmod_FMusic
 * Method:    nFMUSIC_LoadSongEx
 * Signature: (Ljava/nio/ByteBuffer;IIIILjava/nio/IntBuffer;II)J
 */
JNIEXPORT jlong JNICALL Java_org_lwjgl_fmod_FMusic_nFMUSIC_1LoadSongEx__Ljava_nio_ByteBuffer_2IIIILjava_nio_IntBuffer_2II
  (JNIEnv *, jclass, jobject, jint, jint, jint, jint, jobject, jint, jint);

/*
 * Class:     org_lwjgl_fmod_FMusic
 * Method:    nFMUSIC_LoadSongEx
 * Signature: (Ljava/lang/String;IIILjava/nio/IntBuffer;II)J
 */
JNIEXPORT jlong JNICALL Java_org_lwjgl_fmod_FMusic_nFMUSIC_1LoadSongEx__Ljava_lang_String_2IIILjava_nio_IntBuffer_2II
  (JNIEnv *, jclass, jstring, jint, jint, jint, jobject, jint, jint);

/*
 * Class:     org_lwjgl_fmod_FMusic
 * Method:    nFMUSIC_GetOpenState
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_lwjgl_fmod_FMusic_nFMUSIC_1GetOpenState
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_lwjgl_fmod_FMusic
 * Method:    nFMUSIC_FreeSong
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_lwjgl_fmod_FMusic_nFMUSIC_1FreeSong
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_lwjgl_fmod_FMusic
 * Method:    nFMUSIC_PlaySong
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_lwjgl_fmod_FMusic_nFMUSIC_1PlaySong
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_lwjgl_fmod_FMusic
 * Method:    nFMUSIC_StopSong
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_lwjgl_fmod_FMusic_nFMUSIC_1StopSong
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_lwjgl_fmod_FMusic
 * Method:    FMUSIC_StopAllSongs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_fmod_FMusic_FMUSIC_1StopAllSongs
  (JNIEnv *, jclass);

/*
 * Class:     org_lwjgl_fmod_FMusic
 * Method:    nFMUSIC_SetZxxCallback
 * Signature: (JLorg/lwjgl/fmod/callbacks/FMusicCallback;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_lwjgl_fmod_FMusic_nFMUSIC_1SetZxxCallback
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_lwjgl_fmod_FMusic
 * Method:    nFMUSIC_SetRowCallback
 * Signature: (JLorg/lwjgl/fmod/callbacks/FMusicCallback;I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_lwjgl_fmod_FMusic_nFMUSIC_1SetRowCallback
  (JNIEnv *, jclass, jlong, jobject, jint);

/*
 * Class:     org_lwjgl_fmod_FMusic
 * Method:    nFMUSIC_SetOrderCallback
 * Signature: (JLorg/lwjgl/fmod/callbacks/FMusicCallback;I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_lwjgl_fmod_FMusic_nFMUSIC_1SetOrderCallback
  (JNIEnv *, jclass, jlong, jobject, jint);

/*
 * Class:     org_lwjgl_fmod_FMusic
 * Method:    nFMUSIC_SetInstCallback
 * Signature: (JLorg/lwjgl/fmod/callbacks/FMusicCallback;I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_lwjgl_fmod_FMusic_nFMUSIC_1SetInstCallback
  (JNIEnv *, jclass, jlong, jobject, jint);

/*
 * Class:     org_lwjgl_fmod_FMusic
 * Method:    nFMUSIC_SetSample
 * Signature: (JIJ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_lwjgl_fmod_FMusic_nFMUSIC_1SetSample
  (JNIEnv *, jclass, jlong, jint, jlong);

/*
 * Class:     org_lwjgl_fmod_FMusic
 * Method:    nFMUSIC_SetUserData
 * Signature: (JLjava/nio/ByteBuffer;I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_lwjgl_fmod_FMusic_nFMUSIC_1SetUserData
  (JNIEnv *, jclass, jlong, jobject, jint);

/*
 * Class:     org_lwjgl_fmod_FMusic
 * Method:    nFMUSIC_OptimizeChannels
 * Signature: (JII)Z
 */
JNIEXPORT jboolean JNICALL Java_org_lwjgl_fmod_FMusic_nFMUSIC_1OptimizeChannels
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     org_lwjgl_fmod_FMusic
 * Method:    FMUSIC_SetReverb
 * Signature: (Z)Z
 */
JNIEXPORT jboolean JNICALL Java_org_lwjgl_fmod_FMusic_FMUSIC_1SetReverb
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     org_lwjgl_fmod_FMusic
 * Method:    nFMUSIC_SetLooping
 * Signature: (JZ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_lwjgl_fmod_FMusic_nFMUSIC_1SetLooping
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     org_lwjgl_fmod_FMusic
 * Method:    nFMUSIC_SetOrder
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_org_lwjgl_fmod_FMusic_nFMUSIC_1SetOrder
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_lwjgl_fmod_FMusic
 * Method:    nFMUSIC_SetPaused
 * Signature: (JZ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_lwjgl_fmod_FMusic_nFMUSIC_1SetPaused
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     org_lwjgl_fmod_FMusic
 * Method:    nFMUSIC_SetMasterVolume
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_org_lwjgl_fmod_FMusic_nFMUSIC_1SetMasterVolume
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_lwjgl_fmod_FMusic
 * Method:    nFMUSIC_SetMasterSpeed
 * Signature: (JF)Z
 */
JNIEXPORT jboolean JNICALL Java_org_lwjgl_fmod_FMusic_nFMUSIC_1SetMasterSpeed
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     org_lwjgl_fmod_FMusic
 * Method:    nFMUSIC_SetPanSeperation
 * Signature: (JF)Z
 */
JNIEXPORT jboolean JNICALL Java_org_lwjgl_fmod_FMusic_nFMUSIC_1SetPanSeperation
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     org_lwjgl_fmod_FMusic
 * Method:    nFMUSIC_GetName
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_lwjgl_fmod_FMusic_nFMUSIC_1GetName
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_lwjgl_fmod_FMusic
 * Method:    nFMUSIC_GetType
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_lwjgl_fmod_FMusic_nFMUSIC_1GetType
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_lwjgl_fmod_FMusic
 * Method:    nFMUSIC_GetNumOrders
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_lwjgl_fmod_FMusic_nFMUSIC_1GetNumOrders
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_lwjgl_fmod_FMusic
 * Method:    nFMUSIC_GetNumPatterns
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_lwjgl_fmod_FMusic_nFMUSIC_1GetNumPatterns
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_lwjgl_fmod_FMusic
 * Method:    nFMUSIC_GetNumInstruments
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_lwjgl_fmod_FMusic_nFMUSIC_1GetNumInstruments
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_lwjgl_fmod_FMusic
 * Method:    nFMUSIC_GetNumSamples
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_lwjgl_fmod_FMusic_nFMUSIC_1GetNumSamples
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_lwjgl_fmod_FMusic
 * Method:    nFMUSIC_GetNumChannels
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_lwjgl_fmod_FMusic_nFMUSIC_1GetNumChannels
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_lwjgl_fmod_FMusic
 * Method:    nFMUSIC_GetSample
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_org_lwjgl_fmod_FMusic_nFMUSIC_1GetSample
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_lwjgl_fmod_FMusic
 * Method:    nFMUSIC_GetPatternLength
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_org_lwjgl_fmod_FMusic_nFMUSIC_1GetPatternLength
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_lwjgl_fmod_FMusic
 * Method:    nFMUSIC_IsFinished
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_lwjgl_fmod_FMusic_nFMUSIC_1IsFinished
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_lwjgl_fmod_FMusic
 * Method:    nFMUSIC_IsPlaying
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_lwjgl_fmod_FMusic_nFMUSIC_1IsPlaying
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_lwjgl_fmod_FMusic
 * Method:    nFMUSIC_GetMasterVolume
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_lwjgl_fmod_FMusic_nFMUSIC_1GetMasterVolume
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_lwjgl_fmod_FMusic
 * Method:    nFMUSIC_GetGlobalVolume
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_lwjgl_fmod_FMusic_nFMUSIC_1GetGlobalVolume
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_lwjgl_fmod_FMusic
 * Method:    nFMUSIC_GetOrder
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_lwjgl_fmod_FMusic_nFMUSIC_1GetOrder
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_lwjgl_fmod_FMusic
 * Method:    nFMUSIC_GetPattern
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_lwjgl_fmod_FMusic_nFMUSIC_1GetPattern
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_lwjgl_fmod_FMusic
 * Method:    nFMUSIC_GetSpeed
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_lwjgl_fmod_FMusic_nFMUSIC_1GetSpeed
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_lwjgl_fmod_FMusic
 * Method:    nFMUSIC_GetBPM
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_lwjgl_fmod_FMusic_nFMUSIC_1GetBPM
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_lwjgl_fmod_FMusic
 * Method:    nFMUSIC_GetRow
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_lwjgl_fmod_FMusic_nFMUSIC_1GetRow
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_lwjgl_fmod_FMusic
 * Method:    nFMUSIC_GetPaused
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_lwjgl_fmod_FMusic_nFMUSIC_1GetPaused
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_lwjgl_fmod_FMusic
 * Method:    nFMUSIC_GetTime
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_lwjgl_fmod_FMusic_nFMUSIC_1GetTime
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_lwjgl_fmod_FMusic
 * Method:    nFMUSIC_GetRealChannel
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_org_lwjgl_fmod_FMusic_nFMUSIC_1GetRealChannel
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_lwjgl_fmod_FMusic
 * Method:    nFMUSIC_GetUserData
 * Signature: (J)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_org_lwjgl_fmod_FMusic_nFMUSIC_1GetUserData
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
