/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_lwjgl_devil_ILUT */

#ifndef _Included_org_lwjgl_devil_ILUT
#define _Included_org_lwjgl_devil_ILUT
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_lwjgl_devil_ILUT
 * Method:    initNativeStubs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_devil_ILUT_initNativeStubs
  (JNIEnv *, jclass);

/*
 * Class:     org_lwjgl_devil_ILUT
 * Method:    resetNativeStubs
 * Signature: (Ljava/lang/Class;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_devil_ILUT_resetNativeStubs
  (JNIEnv *, jclass, jclass);

/*
 * Class:     org_lwjgl_devil_ILUT
 * Method:    nCreate
 * Signature: ([Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_devil_ILUT_nCreate
  (JNIEnv *, jclass, jobjectArray);

/*
 * Class:     org_lwjgl_devil_ILUT
 * Method:    nDestroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_devil_ILUT_nDestroy
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
